import conPanna.Structural
import examples.bakery

/-!
# ACU certification experiment — start here

This is the ONE active Lean prototype. The companion certification2.maude
manually runs the same primitive derivation; no generated model/trace importer
is implemented yet. Run: lake env lean certification2.lean

Reading order:
1. For the user-facing result, jump to IndexedExample.wrapped_two_unifiers
   near the bottom: one native equation, two unifiers, one certification proof.
2. The model and ONE `certify_structural` annotation immediately precede it.
   Registration data and syntactic round-trip proofs are generated automatically.
   There are no user-provided freeness, reflection, or unification proofs.
3. Everything before the model is LIBRARY PROTOTYPE code: ACU proof rules,
   generic transport and wrapper metatheorems. Indexed constructor semantics and
   registration generation now live in conPanna.Structural, not duplicated here.

Scope/status:
* Primitive certificate replay, wrapper inversion and the native example are
  proved without admissions. Constructor congruence has arbitrary typed arity.
* Semantic decomposition is tested for ONE ACU sort plus a free unary wrapper.
  This is not a complete ACU search algorithm or a Bakery certificate yet.
* Native proofs use `=[WrappedTheory.certified]`, the library's new sort-indexed
  relation. Its map to existing Structural.EqMod is proved; the reverse is NOT.
  Existing Theory/EqMod and narrowing semantics keep their original meaning.
  Keeping sort/argument indices avoids recovering domains from equality of
  arbitrary Lean function types, the obstacle in the discarded diagnostic.
* Automatic registration currently accepts one ACU datatype with nullary atoms
  and one free unary state wrapper. Other signatures are rejected explicitly.
  Broader signatures and migration of narrowing remain next steps, not extra
  user semantic proof obligations. No new experimental Lean files were added.

References for the rule-based design:
* Boudet–Contejean, "Syntactic" AC-Unification, CCL 1994, Definition 4 and
  Section 2.2 / Figure 1: exact disjunctions and contextual Mutate/Var-Rep.
  https://doi.org/10.1007/BFb0016849
  https://www.lri.fr/~contejea/publis/1994ccl/main.pdf
  Their algorithm is AC; the ACU rules used here are proved below, not assumed.
* Jouannaud–Kirchner, Solving equations in abstract algebras: A rule-based
  survey of unification, Computational Logic, MIT Press, 1991.

The external certificate is first-order DATA, without Lean proofs/functions.
Lists appear in generic metatheorems, not as a Diophantine/unification search
hidden inside the checker. Polynomial checking is a target, not proved here.
-/

namespace Certification2

/-! ## General semantic metatheorems (not problem certificates) -/

/-- Ground terms of one ACU component. `s` is a genuine type index. -/
inductive Value {Sorts : Type} (s : Sorts) where
  | zero
  | atom (symbol : Nat)
  | add (left right : Value s)
  deriving Repr, DecidableEq

variable {Sorts : Type} {s : Sorts}

/-- Exactly the congruence generated by ACU, with no extra algebraic laws. -/
inductive ACU : Value s → Value s → Prop where
  | refl (a) : ACU a a
  | symm {a b} : ACU a b → ACU b a
  | trans {a b c} : ACU a b → ACU b c → ACU a c
  | congr {a b c d} : ACU a b → ACU c d → ACU (.add a c) (.add b d)
  | assoc (a b c) : ACU (.add (.add a b) c) (.add a (.add b c))
  | comm (a b) : ACU (.add a b) (.add b a)
  | unit (a) : ACU (.add .zero a) a

namespace Value

def flatten : Value s → List Nat
  | .zero => []
  | .atom a => [a]
  | .add a b => a.flatten ++ b.flatten

def ofList : List Nat → Value s
  | [] => .zero
  | a :: rest => .add (.atom a) (ofList rest)

@[simp] theorem flatten_ofList (xs : List Nat) :
    (ofList (s := s) xs).flatten = xs := by
  induction xs with
  | nil => rfl
  | cons a rest ih => simp [ofList, flatten, ih]

end Value

namespace ACU

theorem unitRight (a : Value s) : ACU (.add a .zero) a :=
  (comm _ _).trans (unit _)

theorem exchange (a b c : Value s) :
    ACU (.add a (.add b c)) (.add b (.add a c)) :=
  (assoc _ _ _).symm.trans ((congr (comm _ _) (refl _)).trans (assoc _ _ _))

theorem flatten_perm {a b : Value s} (h : ACU a b) :
    a.flatten.Perm b.flatten := by
  induction h with
  | refl => exact .refl _
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | congr _ _ ih₁ ih₂ => exact ih₁.append ih₂
  | assoc => simp [Value.flatten, List.append_assoc]
  | comm => exact List.perm_append_comm
  | unit => exact .refl _

theorem ofList_append (xs ys : List Nat) :
    ACU (Value.ofList (s := s) (xs ++ ys))
      (.add (Value.ofList xs) (Value.ofList ys)) := by
  induction xs with
  | nil => exact (unit _).symm
  | cons a rest ih =>
      exact (congr (refl _) ih).trans (assoc _ _ _).symm

theorem normalize (a : Value s) : ACU a (Value.ofList a.flatten) := by
  induction a with
  | zero => exact refl _
  | atom => exact (unitRight _).symm
  | add a b ih₁ ih₂ =>
      exact (congr ih₁ ih₂).trans (ofList_append _ _).symm

theorem ofList_perm {xs ys : List Nat} (h : xs.Perm ys) :
    ACU (Value.ofList (s := s) xs) (Value.ofList ys) := by
  induction h with
  | nil => exact refl _
  | cons a _ ih => exact congr (refl _) ih
  | swap => exact exchange _ _ _
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Faithfulness is proved, rather than assumed as a model registration field. -/
theorem iff_perm (a b : Value s) : ACU a b ↔ a.flatten.Perm b.flatten :=
  ⟨flatten_perm, fun h => (normalize a).trans ((ofList_perm h).trans (normalize b).symm)⟩

theorem cancel (a b c : Value s) :
    ACU (.add a c) (.add b c) ↔ ACU a b := by
  simp only [iff_perm, Value.flatten, List.perm_append_right_iff]

theorem split_zero (a b : Value s) :
    ACU (.add a b) .zero ↔ ACU a .zero ∧ ACU b .zero := by
  simp [iff_perm, Value.flatten]

theorem split_atom (a b : Value s) (k : Nat) :
    ACU (.add a b) (.atom k) ↔
      (ACU a .zero ∧ ACU b (.atom k)) ∨
      (ACU a (.atom k) ∧ ACU b .zero) := by
  simp only [iff_perm, Value.flatten, List.perm_nil, List.perm_singleton]
  cases ha : a.flatten with
  | nil => simp
  | cons x xs =>
      cases hb : b.flatten with
      | nil => simp
      | cons y ys => simp

end ACU

/-- General refinement of four bags; auxiliary to the ACU Mutate theorem. -/
theorem perm_refine {α : Type} (a b c d : List α)
    (h : (a ++ b).Perm (c ++ d)) :
    ∃ p q r t, a.Perm (p ++ q) ∧ b.Perm (r ++ t) ∧
      c.Perm (p ++ r) ∧ d.Perm (q ++ t) := by
  induction a generalizing c d with
  | nil => exact ⟨[], [], c, d, .refl _, h, .refl _, .refl _⟩
  | cons x a ih =>
      have hm : x ∈ c ++ d := h.mem_iff.mp (by simp)
      rcases List.mem_append.mp hm with hc | hd
      · rcases List.mem_iff_append.mp hc with ⟨l, r, rfl⟩
        have hp : (l ++ x :: r ++ d).Perm (x :: ((l ++ r) ++ d)) := by
          simpa only [List.cons_append] using
            (List.perm_middle (a := x) (l₁ := l) (l₂ := r)).append_right d
        obtain ⟨p, q, r', t, ha, hb, hc, hd⟩ := ih (l ++ r) d (h.trans hp).cons_inv
        exact ⟨x :: p, q, r', t, ha.cons x, hb,
          List.perm_middle.trans (hc.cons x), hd⟩
      · rcases List.mem_iff_append.mp hd with ⟨l, r, rfl⟩
        have hp : (c ++ (l ++ x :: r)).Perm (x :: (c ++ (l ++ r))) := by
          exact ((List.perm_middle (a := x) (l₁ := l) (l₂ := r)).append_left c).trans
            List.perm_middle
        obtain ⟨p, q, r', t, ha, hb, hc, hd⟩ := ih c (l ++ r) (h.trans hp).cons_inv
        exact ⟨p, x :: q, r', t, (ha.cons x).trans List.perm_middle.symm,
          hb, hc, List.perm_middle.trans (hd.cons x)⟩

/--
ACU specialization of Mutate for the generic head equation x+y = u+v.
Empty pieces subsume the smaller overlap shapes needed in AC without a unit.

  a+b ≈ c+d
  ----------------------------------------------------- [MutateACU]
  ∃ p q r t, a≈p+q ∧ b≈r+t ∧ c≈p+r ∧ d≈q+t

The equivalence proves BOTH completeness and soundness of this rule.
-/
theorem ACU.mutate (a b c d : Value s) :
    ACU (.add a b) (.add c d) ↔
      ∃ p q r t, ACU a (.add p q) ∧ ACU b (.add r t) ∧
        ACU c (.add p r) ∧ ACU d (.add q t) := by
  constructor
  · intro h
    obtain ⟨p, q, r, t, ha, hb, hc, hd⟩ :=
      perm_refine a.flatten b.flatten c.flatten d.flatten h.flatten_perm
    refine ⟨Value.ofList p, Value.ofList q, Value.ofList r, Value.ofList t, ?_⟩
    simpa only [ACU.iff_perm, Value.flatten, Value.flatten_ofList] using ⟨ha, hb, hc, hd⟩
  · rintro ⟨p, q, r, t, ha, hb, hc, hd⟩
    have middle : ACU (.add (.add p q) (.add r t)) (.add (.add p r) (.add q t)) :=
      (ACU.assoc _ _ _).trans
        ((ACU.congr (ACU.refl _) (ACU.exchange _ _ _)).trans (ACU.assoc _ _ _).symm)
    exact (ACU.congr ha hb).trans (middle.trans (ACU.congr hc hd).symm)

/-! ## Portable syntax and certificate format -/

/-- Variables and atom symbols have separate namespaces. -/
inductive Term {Sorts : Type} (s : Sorts) where
  | var (index : Nat)
  | atom (symbol : Nat)
  | zero
  | add (left right : Term s)
  deriving Repr, DecidableEq

abbrev Assignment (s : Sorts) := Nat → Value s

def push (v : Value s) (ρ : Assignment s) : Assignment s
  | 0 => v
  | n + 1 => ρ n

namespace Term

def eval : Term s → Assignment s → Value s
  | .var n, ρ => ρ n
  | .atom k, _ => .atom k
  | .zero, _ => .zero
  | .add a b, ρ => .add (a.eval ρ) (b.eval ρ)

/-- De Bruijn lifting prevents capture when Mutate introduces witnesses. -/
def lift : Term s → Term s
  | .var n => .var (n + 1)
  | .atom k => .atom k
  | .zero => .zero
  | .add a b => .add a.lift b.lift

@[simp] theorem eval_lift (a : Term s) (v : Value s) (ρ : Assignment s) :
    a.lift.eval (push v ρ) = a.eval ρ := by
  induction a with
  | var => rfl
  | atom => rfl
  | zero => rfl
  | add a b ih₁ ih₂ => simp only [lift, eval, ih₁, ih₂]

end Term

/-- Explicit formulas, not arbitrary Lean propositions or closures. -/
inductive Formula {Sorts : Type} (s : Sorts) where
  | truth
  | falsity
  | eqn (left right : Term s)
  | conj (left right : Formula s)
  | disj (left right : Formula s)
  | ex (body : Formula s)
  deriving Repr, DecidableEq

def Formula.Holds : Formula s → Assignment s → Prop
  | .truth, _ => True
  | .falsity, _ => False
  | .eqn a b, ρ => ACU (a.eval ρ) (b.eval ρ)
  | .conj p q, ρ => p.Holds ρ ∧ q.Holds ρ
  | .disj p q, ρ => p.Holds ρ ∨ q.Holds ρ
  | .ex p, ρ => ∃ v, p.Holds (push v ρ)

def Equivalent (p q : Formula s) : Prop := ∀ ρ, p.Holds ρ ↔ q.Holds ρ

/-! ### Capture-avoiding replacement and existential elimination

Var-Rep / EQE, specialized to our explicit binder syntax:

    ∃ x. (x ≈ t ∧ P)    <=>    P[t/x]       (x not free in t)

This is replacement MODULO ACU, not replacement by literal Lean equality.
`Holds_congr` is essential: every formula in this calculus respects ACU in
its variable assignments. This does not assert that arbitrary user constraints
have that property. Substitution under a binder lifts the replacement terms.
-/

def Term.subst (σ : Nat → Term s) : Term s → Term s
  | .var n => σ n
  | .atom k => .atom k
  | .zero => .zero
  | .add a b => .add (a.subst σ) (b.subst σ)

theorem Term.eval_subst (a : Term s) (σ : Nat → Term s) (ρ : Assignment s) :
    (a.subst σ).eval ρ = a.eval (fun n => (σ n).eval ρ) := by
  induction a <;> simp_all [subst, eval]

def upSubst (σ : Nat → Term s) : Nat → Term s
  | 0 => .var 0
  | n + 1 => (σ n).lift

def Formula.subst (σ : Nat → Term s) : Formula s → Formula s
  | .truth => .truth
  | .falsity => .falsity
  | .eqn a b => .eqn (a.subst σ) (b.subst σ)
  | .conj p q => .conj (p.subst σ) (q.subst σ)
  | .disj p q => .disj (p.subst σ) (q.subst σ)
  | .ex p => .ex (p.subst (upSubst σ))

theorem Formula.holds_subst (p : Formula s) (σ : Nat → Term s) (ρ : Assignment s) :
    (p.subst σ).Holds ρ ↔ p.Holds (fun n => (σ n).eval ρ) := by
  induction p generalizing σ ρ with
  | truth => rfl
  | falsity => rfl
  | eqn => simp only [subst, Holds, Term.eval_subst]
  | conj p q hp hq => exact and_congr (hp σ ρ) (hq σ ρ)
  | disj p q hp hq => exact or_congr (hp σ ρ) (hq σ ρ)
  | ex p hp =>
      apply exists_congr
      intro v
      have he : (fun n => (upSubst σ n).eval (push v ρ)) =
          push v (fun n => (σ n).eval ρ) := by
        funext n
        cases n <;> simp [upSubst, push, Term.eval]
      exact (hp _ _).trans (he ▸ Iff.rfl)

theorem Term.eval_congr (a : Term s) {ρ τ : Assignment s}
    (h : ∀ n, ACU (ρ n) (τ n)) : ACU (a.eval ρ) (a.eval τ) := by
  induction a with
  | var n => exact h n
  | atom => exact .refl _
  | zero => exact .refl _
  | add a b ha hb => exact .congr ha hb

theorem Formula.holds_congr (p : Formula s) {ρ τ : Assignment s}
    (h : ∀ n, ACU (ρ n) (τ n)) : p.Holds ρ ↔ p.Holds τ := by
  induction p generalizing ρ τ with
  | truth => rfl
  | falsity => rfl
  | eqn a b => exact
      ⟨fun e => (a.eval_congr h).symm.trans (e.trans (b.eval_congr h)),
       fun e => (a.eval_congr h).trans (e.trans (b.eval_congr h).symm)⟩
  | conj p q hp hq => exact and_congr (hp h) (hq h)
  | disj p q hp hq => exact or_congr (hp h) (hq h)
  | ex p hp =>
      apply exists_congr
      intro v
      apply hp
      intro n
      cases n with
      | zero => exact .refl _
      | succ n => exact h n

/-- Inverse of lift, undefined if the term mentions the variable being removed. -/
def Term.lower : Term s → Option (Term s)
  | .var 0 => none
  | .var (n + 1) => some (.var n)
  | .atom k => some (.atom k)
  | .zero => some .zero
  | .add a b => return .add (← a.lower) (← b.lower)

theorem Term.lower_lift {a t : Term s} (h : a.lower = some t) : a = t.lift := by
  induction a generalizing t with
  | var n =>
      cases n with
      | zero => simp [lower] at h
      | succ n => cases Option.some.inj h; rfl
  | atom => cases Option.some.inj h; rfl
  | zero => cases Option.some.inj h; rfl
  | add a b ha hb =>
      cases he₁ : a.lower <;> cases he₂ : b.lower <;> simp [lower, he₁, he₂] at h
      cases h
      simp only [lift, ha he₁, hb he₂]

def replaceZero (t : Term s) : Nat → Term s
  | 0 => t
  | n + 1 => .var n

theorem eliminate_correct (t : Term s) (p : Formula s) :
    Equivalent (.ex (.conj (.eqn (.var 0) t.lift) p))
      (p.subst (replaceZero t)) := by
  intro ρ
  rw [Formula.holds_subst]
  have he : (fun n => (replaceZero t n).eval ρ) = push (t.eval ρ) ρ := by
    funext n
    cases n <;> rfl
  rw [he]
  change (∃ v, ACU v (t.lift.eval (push v ρ)) ∧ p.Holds (push v ρ)) ↔ _
  simp only [Term.eval_lift]
  constructor
  · rintro ⟨v, hv, hp⟩
    apply (p.holds_congr (ρ := push v ρ) (τ := push (t.eval ρ) ρ) ?_).mp hp
    intro n
    cases n with
    | zero => exact hv
    | succ => exact .refl _
  · intro hp
    exact ⟨t.eval ρ, .refl _, hp⟩

/-- Move a binding to the front of a conjunction tree, retaining every sibling.
No disjunction is crossed. The returned term is already lowered/freshness-checked. -/
def binding (p : Formula s) :
    Option { pair : Term s × Formula s //
      Equivalent p (.conj (.eqn (.var 0) pair.1.lift) pair.2) } :=
  match p with
  | .eqn (.var 0) t => do
      let u ← t.lower.attach
      return ⟨(u.val, .truth), by
        have ht := Term.lower_lift u.property
        intro ρ
        change ACU (ρ 0) (t.eval ρ) ↔ ACU (ρ 0) (u.val.lift.eval ρ) ∧ True
        simp only [ht, and_true]⟩
  | .conj p q =>
      match binding p with
      | some ⟨(t, p'), h⟩ => some ⟨(t, .conj p' q), fun ρ => by
          change p.Holds ρ ∧ q.Holds ρ ↔ _
          rw [h ρ]
          exact and_assoc⟩
      | none => do
          let ⟨(t, q'), h⟩ ← binding q
          return ⟨(t, .conj p q'), fun ρ => by
            change p.Holds ρ ∧ q.Holds ρ ↔ _
            rw [h ρ]
            exact and_left_comm⟩
  | _ => none

def swapZeroOne : Nat → Term s
  | 0 => .var 1
  | 1 => .var 0
  | n + 2 => .var (n + 2)

theorem exchange_exists_correct (p : Formula s) :
    Equivalent (.ex (.ex p)) (.ex (.ex (p.subst swapZeroOne))) := by
  intro ρ
  have he (v w : Value s) :
      (fun n => (swapZeroOne n).eval (push w (push v ρ))) = push v (push w ρ) := by
    funext n
    cases n with
    | zero => rfl
    | succ n => cases n <;> rfl
  change (∃ v w, p.Holds (push w (push v ρ))) ↔ _
  simp only [Formula.Holds, Formula.holds_subst, he]
  exact exists_comm

/-- Only unit simplification, not ACU unification or matching. -/
def Term.units : (a : Term s) → { b : Term s // ∀ ρ, ACU (a.eval ρ) (b.eval ρ) }
  | .add a b =>
      let ⟨a', ha⟩ := a.units
      let ⟨b', hb⟩ := b.units
      match a', b' with
      | .zero, b' => ⟨b', fun ρ => (ACU.congr (ha ρ) (hb ρ)).trans (ACU.unit _)⟩
      | a', .zero => ⟨a', fun ρ => (ACU.congr (ha ρ) (hb ρ)).trans (ACU.unitRight _)⟩
      | a', b' => ⟨.add a' b', fun ρ => ACU.congr (ha ρ) (hb ρ)⟩
  | .zero => ⟨.zero, fun _ => .refl _⟩
  | .var n => ⟨.var n, fun _ => .refl _⟩
  | .atom k => ⟨.atom k, fun _ => .refl _⟩

/-- Deterministic cleanup: remove units in terms and True conjuncts in formulas.
It neither deletes alternatives nor decides satisfiability. -/
def Formula.cleanup : (p : Formula s) → { q : Formula s // Equivalent p q }
  | .eqn a b =>
      let ⟨a', ha⟩ := a.units
      let ⟨b', hb⟩ := b.units
      ⟨.eqn a' b', fun ρ =>
        ⟨fun h => (ha ρ).symm.trans (h.trans (hb ρ)),
         fun h => (ha ρ).trans (h.trans (hb ρ).symm)⟩⟩
  | .conj p q =>
      let ⟨p', hp⟩ := p.cleanup
      let ⟨q', hq⟩ := q.cleanup
      match p', q' with
      | .truth, q' => ⟨q', fun ρ => (and_congr (hp ρ) (hq ρ)).trans (by
          simp only [Holds, true_and])⟩
      | p', .truth => ⟨p', fun ρ => (and_congr (hp ρ) (hq ρ)).trans (by
          simp only [Holds, and_true])⟩
      | p', q' => ⟨.conj p' q', fun ρ => and_congr (hp ρ) (hq ρ)⟩
  | .disj p q =>
      let ⟨p', hp⟩ := p.cleanup
      let ⟨q', hq⟩ := q.cleanup
      ⟨.disj p' q', fun ρ => or_congr (hp ρ) (hq ρ)⟩
  | .ex p =>
      let ⟨p', hp⟩ := p.cleanup
      ⟨.ex p', fun ρ => exists_congr (fun v => hp (push v ρ))⟩
  | .truth => ⟨.truth, fun _ => Iff.rfl⟩
  | .falsity => ⟨.falsity, fun _ => Iff.rfl⟩

/-- Every rule has a finite, explicit output, including ALL alternatives. -/
inductive Rule where
  | mutate | splitAtom | splitZero | cancel
  | symmetry | commLeft | assocLeft | padRight
  | reflexive | clash
  | distributeLeft | distributeRight
  | eliminate | exchangeExists | distributeExists
  | cleanup | swapBranches
  deriving Repr, DecidableEq

/--
This is the external certificate format. No fields contain Lean proofs/functions.
`left`/`right` select a logical conjunct/disjunct, `under` enters an existential.
Maude can mirror these constructors directly. Term/equation positions are explicit
in the tree; no matching modulo ACU is performed during replay.
-/
inductive Certificate where
  | rule (tag : Rule)
  | seq (first second : Certificate)
  | left (proof : Certificate)
  | right (proof : Certificate)
  | under (proof : Certificate)
  deriving Repr, DecidableEq

/-- Four fresh variables are indices 3,2,1,0 after four nested binders. -/
def mutation (a b c d : Term s) : Formula s :=
  .ex (.ex (.ex (.ex (
    .conj (.eqn a.lift.lift.lift.lift (.add (.var 3) (.var 2)))
    (.conj (.eqn b.lift.lift.lift.lift (.add (.var 1) (.var 0)))
    (.conj (.eqn c.lift.lift.lift.lift (.add (.var 3) (.var 1)))
           (.eqn d.lift.lift.lift.lift (.add (.var 2) (.var 0)))))))))

theorem mutation_correct (a b c d : Term s) :
    Equivalent (.eqn (.add a b) (.add c d)) (mutation a b c d) := by
  intro ρ
  simp only [mutation, Formula.Holds, Term.eval_lift, Term.eval, push]
  exact ACU.mutate _ _ _ _

/-- Claimed solved output, with two independently scoped parameter pairs. It is
just formula data; the primitive trace below must certify it. -/
def overlapSolutions (a b c : Term s) (k : Nat) : Formula s :=
  .disj
    (.ex (.ex (.conj (.eqn a.lift.lift (.add (.atom k) (.var 1)))
      (.conj (.eqn b.lift.lift (.var 0)) (.eqn c.lift.lift (.add (.var 1) (.var 0)))))))
    (.ex (.ex (.conj (.eqn a.lift.lift (.var 1))
      (.conj (.eqn b.lift.lift (.add (.atom k) (.var 0)))
        (.eqn c.lift.lift (.add (.var 1) (.var 0)))))))

/-! ## Generic proof reconstruction: all reasoning stays in this section -/

variable [DecidableEq Sorts]

/--
A proof-producing local checker. The result carries a Lean proof, but the INPUT
certificate does not. Proof fields erase at execution; the computational work
is constructor inspection and syntactic equality, never unification search.
-/
def applyRule (rule : Rule) (input : Formula s) :
    Option { output : Formula s // Equivalent input output } :=
  match rule, input with
  | .cleanup, p => some p.cleanup
  | .swapBranches, .disj p q => some ⟨.disj q p, fun _ => or_comm⟩
  | .eliminate, .ex p => do
      let ⟨(t, rest), h⟩ ← binding p
      return ⟨rest.subst (replaceZero t), fun ρ =>
        (exists_congr (fun v => h (push v ρ))).trans (eliminate_correct t rest ρ)⟩
  | .exchangeExists, .ex (.ex p) =>
      some ⟨.ex (.ex (p.subst swapZeroOne)), exchange_exists_correct p⟩
  | .distributeExists, .ex (.disj p q) =>
      some ⟨.disj (.ex p) (.ex q), fun _ => exists_or⟩
  | .mutate, .eqn (.add a b) (.add c d) =>
      some ⟨mutation a b c d, mutation_correct a b c d⟩
  | .splitAtom, .eqn (.add a b) (.atom k) =>
      some ⟨.disj (.conj (.eqn a .zero) (.eqn b (.atom k)))
                  (.conj (.eqn a (.atom k)) (.eqn b .zero)),
        fun ρ => ACU.split_atom (a.eval ρ) (b.eval ρ) k⟩
  | .splitZero, .eqn (.add a b) .zero =>
      some ⟨.conj (.eqn a .zero) (.eqn b .zero),
        fun ρ => ACU.split_zero (a.eval ρ) (b.eval ρ)⟩
  | .cancel, .eqn (.add a c) (.add b d) =>
      if h : c = d then
        some ⟨.eqn a b, by subst d; exact fun ρ => ACU.cancel _ _ _⟩
      else none
  | .symmetry, .eqn a b =>
      some ⟨.eqn b a, fun _ => ⟨ACU.symm, ACU.symm⟩⟩
  | .commLeft, .eqn (.add a b) c =>
      some ⟨.eqn (.add b a) c, fun _ =>
        ⟨fun h => (ACU.comm _ _).trans h, fun h => (ACU.comm _ _).trans h⟩⟩
  | .assocLeft, .eqn (.add (.add a b) c) d =>
      some ⟨.eqn (.add a (.add b c)) d, fun _ =>
        ⟨fun h => (ACU.assoc _ _ _).symm.trans h,
         fun h => (ACU.assoc _ _ _).trans h⟩⟩
  | .padRight, .eqn a b =>
      some ⟨.eqn a (.add .zero b), fun _ =>
        ⟨fun h => h.trans (ACU.unit _).symm, fun h => h.trans (ACU.unit _)⟩⟩
  | .reflexive, .eqn a b =>
      if h : a = b then
        some ⟨.truth, by subst b; exact fun _ => ⟨fun _ => trivial, fun _ => .refl _⟩⟩
      else none
  | .clash, .eqn (.atom a) (.atom b) =>
      if h : a = b then none
      else some ⟨.falsity, fun _ => ⟨fun hab => h (by
        simpa only [Term.eval, Value.flatten, List.singleton_perm_singleton] using hab.flatten_perm),
        False.elim⟩⟩
  | .distributeLeft, .conj (.disj p q) r =>
      some ⟨.disj (.conj p r) (.conj q r), by
        intro ρ
        change (p.Holds ρ ∨ q.Holds ρ) ∧ r.Holds ρ ↔ _
        constructor
        · rintro ⟨hp | hq, hr⟩
          · exact Or.inl ⟨hp, hr⟩
          · exact Or.inr ⟨hq, hr⟩
        · rintro (⟨hp, hr⟩ | ⟨hq, hr⟩)
          · exact ⟨Or.inl hp, hr⟩
          · exact ⟨Or.inr hq, hr⟩⟩
  | .distributeRight, .conj p (.disj q r) =>
      some ⟨.disj (.conj p q) (.conj p r), by
        intro ρ
        change p.Holds ρ ∧ (q.Holds ρ ∨ r.Holds ρ) ↔ _
        constructor
        · rintro ⟨hp, hq | hr⟩
          · exact Or.inl ⟨hp, hq⟩
          · exact Or.inr ⟨hp, hr⟩
        · rintro (⟨hp, hq⟩ | ⟨hp, hr⟩)
          · exact ⟨hp, Or.inl hq⟩
          · exact ⟨hp, Or.inr hr⟩⟩
  | _, _ => none

/--
Replay proves EXACT equivalence. In particular `left` and `right` transform a
branch while retaining its sibling; they never select and discard an alternative.
Only a finite certificate is traversed. No claim about complete proof SEARCH or
the termination of an ACU unification algorithm is made by this definition.
-/
def replay (cert : Certificate) (input : Formula s) :
    Option { output : Formula s // Equivalent input output } := do
  match cert with
  | .rule tag => applyRule tag input
  | .seq first second =>
      let ⟨middle, h₁⟩ ← replay first input
      let ⟨output, h₂⟩ ← replay second middle
      return ⟨output, fun ρ => (h₁ ρ).trans (h₂ ρ)⟩
  | .left cert =>
      match input with
      | .conj p q =>
          let ⟨p', h⟩ ← replay cert p
          return ⟨.conj p' q, fun ρ => and_congr (h ρ) Iff.rfl⟩
      | .disj p q =>
          let ⟨p', h⟩ ← replay cert p
          return ⟨.disj p' q, fun ρ => or_congr (h ρ) Iff.rfl⟩
      | _ => none
  | .right cert =>
      match input with
      | .conj p q =>
          let ⟨q', h⟩ ← replay cert q
          return ⟨.conj p q', fun ρ => and_congr Iff.rfl (h ρ)⟩
      | .disj p q =>
          let ⟨q', h⟩ ← replay cert q
          return ⟨.disj p q', fun ρ => or_congr Iff.rfl (h ρ)⟩
      | _ => none
  | .under cert =>
      match input with
      | .ex p =>
          let ⟨p', h⟩ ← replay cert p
          return ⟨.ex p', fun ρ => exists_congr (fun v => h (push v ρ))⟩
      | _ => none

/-- The externally proposed output must match the entire reconstructed output. -/
def check (input output : Formula s) (cert : Certificate) : Bool :=
  match replay cert input with
  | none => false
  | some result => decide (result.val = output)

/-- The only theorem needed by the certification examples below. -/
theorem check_exact (input output : Formula s) (cert : Certificate)
    (accepted : check input output cert = true) : Equivalent input output := by
  cases hr : replay cert input with
  | none => simp [check, hr] at accepted
  | some result =>
      have ho : result.val = output := of_decide_eq_true (by
        simpa only [check, hr] using accepted)
      exact ho ▸ result.property

theorem check_complete (input output : Formula s) (cert : Certificate)
    (accepted : check input output cert = true) (ρ : Assignment s) :
    input.Holds ρ → output.Holds ρ := (check_exact input output cert accepted ρ).mp

theorem check_sound (input output : Formula s) (cert : Certificate)
    (accepted : check input output cert = true) (ρ : Assignment s) :
    output.Holds ρ → input.Holds ρ := (check_exact input output cert accepted ρ).mpr


end Certification2

namespace Certification2

variable {Sorts : Type} {s : Sorts}

/-! ## Generic certificate transport (independent of the example)

Formulas are positive/existential, so a homomorphism preserving the relation
transports satisfaction forwards. Use encode and decode in opposite directions
to lift a checked iff. `allowed` restricts literal symbols in the PROBLEM and
ANSWER; existential witnesses need not already be encoded native values.
Decoding them supplies native witnesses. No feasibility decision is involved.
-/

structure Semantics (α : Type) where
  zero : α
  atom : Nat → α
  add : α → α → α
  rel : α → α → Prop

def portable (s : Sorts) : Semantics (Value s) :=
  ⟨.zero, .atom, .add, ACU⟩

def Term.denote {α : Type} (m : Semantics α) (ρ : Nat → α) : Term s → α
  | .var n => ρ n
  | .atom n => m.atom n
  | .zero => m.zero
  | .add a b => m.add (a.denote m ρ) (b.denote m ρ)

def Formula.sat {α : Type} (m : Semantics α) (ρ : Nat → α) : Formula s → Prop
  | .truth => True
  | .falsity => False
  | .eqn a b => m.rel (a.denote m ρ) (b.denote m ρ)
  | .conj p q => p.sat m ρ ∧ q.sat m ρ
  | .disj p q => p.sat m ρ ∨ q.sat m ρ
  | .ex p => ∃ v, p.sat m (fun n => match n with | 0 => v | n+1 => ρ n)

def Term.uses (allowed : Nat → Prop) : Term s → Prop
  | .var _ | .zero => True
  | .atom n => allowed n
  | .add a b => a.uses allowed ∧ b.uses allowed

def Formula.uses (allowed : Nat → Prop) : Formula s → Prop
  | .truth | .falsity => True
  | .eqn a b => a.uses allowed ∧ b.uses allowed
  | .conj p q | .disj p q => p.uses allowed ∧ q.uses allowed
  | .ex p => p.uses allowed

structure Hom {α β : Type} (m : Semantics α) (n : Semantics β)
    (f : α → β) (allowed : Nat → Prop) : Prop where
  zero : f m.zero = n.zero
  atom : ∀ k, allowed k → f (m.atom k) = n.atom k
  add : ∀ a b, f (m.add a b) = n.add (f a) (f b)
  rel : ∀ {a b}, m.rel a b → n.rel (f a) (f b)

theorem Term.map_denote {α β : Type} {m : Semantics α} {n : Semantics β}
    {f : α → β} {allowed : Nat → Prop} (hom : Hom m n f allowed)
    (t : Term s) (ht : t.uses allowed) (ρ : Nat → α) :
    f (t.denote m ρ) = t.denote n (fun i => f (ρ i)) := by
  induction t with
  | var => rfl
  | zero => exact hom.zero
  | atom k => exact hom.atom k ht
  | add a b ha hb =>
      change f (m.add _ _) = n.add _ _
      rw [hom.add, ha ht.1, hb ht.2]

theorem Formula.map_sat {α β : Type} {m : Semantics α} {n : Semantics β}
    {f : α → β} {allowed : Nat → Prop} (hom : Hom m n f allowed)
    (p : Formula s) (hp : p.uses allowed) (ρ : Nat → α) :
    p.sat m ρ → p.sat n (fun i => f (ρ i)) := by
  induction p generalizing ρ with
  | truth => exact fun _ => trivial
  | falsity => exact False.elim
  | eqn a b =>
      intro h
      have h' := hom.rel h
      rwa [a.map_denote hom hp.1 ρ, b.map_denote hom hp.2 ρ] at h'
  | conj p q ihp ihq => exact fun ⟨h₁, h₂⟩ => ⟨ihp hp.1 ρ h₁, ihq hp.2 ρ h₂⟩
  | disj p q ihp ihq =>
      intro h
      exact h.elim (fun h => Or.inl (ihp hp.1 ρ h)) (fun h => Or.inr (ihq hp.2 ρ h))
  | ex p ih =>
      rintro ⟨v, hv⟩
      refine ⟨f v, ?_⟩
      have mapped := ih hp _ hv
      have he : (fun i => f (match i with | 0 => v | n+1 => ρ n)) =
          (fun i => match i with | 0 => f v | n+1 => f (ρ n)) := by
        funext i
        cases i <;> rfl
      rw [he] at mapped
      exact mapped

theorem Term.uses_all (t : Term s) : t.uses (fun _ => True) := by
  induction t <;> simp_all [uses]

theorem Formula.uses_all (p : Formula s) : p.uses (fun _ => True) := by
  induction p <;> simp_all [uses, Term.uses_all]

theorem Term.denote_portable (t : Term s) (ρ : Assignment s) :
    t.denote (portable s) ρ = t.eval ρ := by
  induction t <;> simp_all [denote, eval, portable]

theorem Formula.sat_portable (p : Formula s) (ρ : Assignment s) :
    p.sat (portable s) ρ ↔ p.Holds ρ := by
  induction p generalizing ρ with
  | truth => rfl
  | falsity => rfl
  | eqn a b =>
      change ACU (a.denote (portable s) ρ) (b.denote (portable s) ρ) ↔ _
      rw [a.denote_portable, b.denote_portable]
      rfl
  | conj p q hp hq => exact and_congr (hp ρ) (hq ρ)
  | disj p q hp hq => exact or_congr (hp ρ) (hq ρ)
  | ex p hp => exact exists_congr (fun v => hp (push v ρ))

/-- A reusable boundary for lifting every checked certificate, not a new
per-problem proof rule. encode/decode need only form a retraction: unused raw
atom codes may collapse under decoding, since source/answer syntax is checked. -/
structure Bridge {α : Type} (m : Semantics α) (s : Sorts) where
  allowed : Nat → Prop
  encode : α → Value s
  decode : Value s → α
  roundtrip : ∀ a, decode (encode a) = a
  forward : Hom m (portable s) encode allowed
  backward : Hom (portable s) m decode (fun _ => True)

theorem Bridge.transport {α : Type} {m : Semantics α} (b : Bridge m s)
    {p q : Formula s} (hp : p.uses b.allowed) (equiv : Equivalent p q)
    (ρ : Nat → α) : p.sat m ρ → q.sat m ρ := by
  intro h
  have rawP := (p.sat_portable _).mp (p.map_sat b.forward hp ρ h)
  have rawQ := (equiv _).mp rawP
  have nativeQ := q.map_sat b.backward q.uses_all _ ((q.sat_portable _).mpr rawQ)
  simpa only [b.roundtrip] using nativeQ

/-- A checked portable certificate lifts BOTH directions to native semantics.
The ONLY per-problem obligations are finite syntax/checker computations. -/
theorem Bridge.check_exact [DecidableEq Sorts] {α : Type} {m : Semantics α}
    (b : Bridge m s) (p q : Formula s) (cert : Certificate)
    (accepted : check p q cert = true)
    (hp : p.uses b.allowed) (hq : q.uses b.allowed) (ρ : Nat → α) :
    p.sat m ρ ↔ q.sat m ρ :=
  let equiv := Certification2.check_exact p q cert accepted
  ⟨b.transport hp equiv ρ, b.transport hq (fun σ => (equiv σ).symm) ρ⟩

end Certification2



/-! ## Library metatheorems for a supported signature fragment

One ACU carrier (with ANY countable atom alphabet) and a free unary wrapper.
These declarations know no user datatype, constructor name or unification problem.
The generic infrastructure above already permits other arities/multiple ACU ops;
the semantic decomposition metatheorems for those fragments remain future work.
-/

namespace Structural.Indexed.Wrapper

open Certification2

variable {Atom : Type}

abbrev Raw := Value SortTag.bag

/-- Encoding of the supported fragment into the existing ACU certificate algebra.
The wrapper is free and unary, so observing its payload loses no information. -/
def algebra (code : Atom → Nat) : Algebra (signature Atom) where
  Carrier := fun _ => Raw
  apply := fun f args => match f, args with
    | .empty, _ => .zero
    | .atom a, _ => .atom (code a)
    | .union, (a, b, _) => .add a b
    | .wrap, (a, _) => a

def observation (code : Atom → Nat) : Model (signature Atom) (algebra code) where
  Rel := fun _ => ACU
  refl := fun _ _ => .refl _
  symm := fun _ {_ _} h => .symm h
  trans := fun _ {_ _ _} h₁ h₂ => .trans h₁ h₂
  congr := by
    intro ss s f a b h
    cases f with
    | empty => exact .refl _
    | atom => exact .refl _
    | union => exact .congr h.1 h.2.1
    | wrap => exact h.1
  «comm» := by intro s op a b; cases op; exact .comm _ _
  «assoc» := by intro s op a b c; cases op; exact .assoc _ _ _
  unit := by intro s op a; cases op; exact .unit _

def rebuildBag (read : Nat → Atom) : Raw → BagTree Atom
  | .zero => empty
  | .atom n => atom (read n)
  | .add a b => union (rebuildBag read a) (rebuildBag read b)

def rebuild (read : Nat → Atom) : (s : SortTag) → Raw → Tree (signature Atom) s
  | .bag, a => rebuildBag read a
  | .configuration, a => wrap (rebuildBag read a)

theorem rebuild_eval (code : Atom → Nat) (read : Nat → Atom)
    (inverse : ∀ a, read (code a) = a) {s : SortTag} (a : Tree (signature Atom) s) :
    rebuild read s (a.eval (algebra code)) = a := by
  apply Tree.rebuild_eval
  intro ss s f args
  cases f with
  | empty => cases args; rfl
  | atom a => cases args; simp only [algebra, rebuild, rebuildBag, inverse, atom, Args.quote]
  | union => rcases args with ⟨a, b, u⟩; cases u; rfl
  | wrap => rcases args with ⟨a, u⟩; cases u; rfl

theorem rebuildBag_congr (read : Nat → Atom) {a b : Raw} (h : ACU a b) :
    Structural.Indexed.Eq (signature Atom) (rebuildBag read a) (rebuildBag read b) := by
  induction h with
  | refl => exact .refl _
  | symm _ ih => exact .symm ih
  | trans _ _ ih₁ ih₂ => exact .trans ih₁ ih₂
  | congr _ _ ih₁ ih₂ =>
      exact Structural.Indexed.Eq.congr (sig := signature Atom) Symbol.union (.cons ih₁ (.cons ih₂ .nil))
  | «comm» => exact Structural.Indexed.Eq.comm (sig := signature Atom) Operator.union _ _
  | «assoc» => exact Structural.Indexed.Eq.assoc (sig := signature Atom) Operator.union _ _ _
  | unit => exact Structural.Indexed.Eq.unit (sig := signature Atom) Operator.union _

/-- Both directions, including free-wrapper inversion. A general library lemma,
not a field supplied during user registration. -/
theorem exact (code : Atom → Nat) (read : Nat → Atom)
    (inverse : ∀ a, read (code a) = a) {s : SortTag}
    (a b : Tree (signature Atom) s) :
    Structural.Indexed.Eq (signature Atom) a b ↔
      ACU (a.eval (algebra code)) (b.eval (algebra code)) := by
  constructor
  · exact Structural.Indexed.Eq.sound _ (observation code)
  · intro h
    have lifted : Structural.Indexed.Eq (signature Atom)
        (rebuild read s (a.eval (algebra code)))
        (rebuild read s (b.eval (algebra code))) := by
      cases s with
      | bag => exact rebuildBag_congr read h
      | configuration =>
          exact Structural.Indexed.Eq.congr (sig := signature Atom) Symbol.wrap (.cons (rebuildBag_congr read h) .nil)
    simpa only [rebuild_eval code read inverse] using lifted

theorem wrap_iff (code : Atom → Nat) (read : Nat → Atom)
    (inverse : ∀ a, read (code a) = a) (a b : BagTree Atom) :
    Structural.Indexed.Eq (signature Atom) (wrap a) (wrap b) ↔ Structural.Indexed.Eq (signature Atom) a b :=
  (exact code read inverse (wrap a) (wrap b)).trans (exact code read inverse a b).symm

/-- Generic native interpretation of the proof system: no model-specific lemmas. -/
def nativeSemantics (reg : Registration (signature Atom)) (read : Nat → Atom) :
    Semantics (reg.Carrier .bag) where
  zero := reg.apply .empty PUnit.unit
  atom := fun n => reg.apply (.atom (read n)) PUnit.unit
  add := fun a b => reg.apply .union (a, b, PUnit.unit)
  rel := NativeEq (signature Atom) reg

/-- Instantiating the checker needs only generated syntax metadata. -/
def checker (reg : Registration (signature Atom)) (code : Atom → Nat) (read : Nat → Atom)
    (inverse : ∀ a, read (code a) = a) : Bridge (nativeSemantics reg read) SortTag.bag where
  allowed := fun n => code (read n) = n
  encode := fun a => (reg.quote .bag a).eval (algebra code)
  decode := fun a => (rebuildBag read a).eval reg.toAlgebra
  roundtrip := by
    intro a
    have h := rebuild_eval code read inverse (reg.quote .bag a)
    exact (congrArg (fun t => t.eval reg.toAlgebra) h).trans (reg.eval_quote .bag a)
  forward := {
    zero := by
      change (reg.quote .bag (reg.apply .empty PUnit.unit)).eval (algebra code) = _
      rw [reg.quote_apply]; rfl
    atom := by
      intro n hn
      change (reg.quote .bag (reg.apply (.atom (read n)) PUnit.unit)).eval (algebra code) = _
      rw [reg.quote_apply]
      change Value.atom (code (read n)) = Value.atom n
      rw [hn]
    add := by
      intro a b
      change (reg.quote .bag (reg.apply .union (a, b, PUnit.unit))).eval (algebra code) = _
      rw [reg.quote_apply]; rfl
    rel := fun h => (exact code read inverse _ _).mp h }
  backward := {
    zero := rfl
    atom := by intro n _; rfl
    add := fun _ _ => rfl
    rel := by
      intro a b h
      change Structural.Indexed.Eq (signature Atom)
        (reg.quote .bag ((rebuildBag read a).eval reg.toAlgebra))
        (reg.quote .bag ((rebuildBag read b).eval reg.toAlgebra))
      rw [Registration.quote_eval, Registration.quote_eval]
      exact rebuildBag_congr read h }

theorem native_wrap_iff (reg : Registration (signature Atom))
    (code : Atom → Nat) (read : Nat → Atom) (inverse : ∀ a, read (code a) = a)
    (a b : reg.Carrier .bag) :
    NativeEq (signature Atom) reg (s := .configuration)
      (reg.apply .wrap (a, PUnit.unit)) (reg.apply .wrap (b, PUnit.unit)) ↔
    NativeEq (signature Atom) reg a b := by
  unfold NativeEq
  rw [reg.quote_apply, reg.quote_apply]
  exact wrap_iff code read inverse _ _

end Structural.Indexed.Wrapper

/-! ## Example certificate data (shared with the Maude experiment) -/

namespace Certification2.Demo

/-- Abbreviations for certificate DATA; no new proof rules. Every sequence ends
with deterministic cleanup. `beneath n` specifies an explicit binder depth. -/
def steps : List Certificate → Certificate
  | [] => .rule .cleanup
  | c :: cs => .seq c (steps cs)

def beneath : Nat → Certificate → Certificate
  | 0, c => c
  | n + 1, c => .under (beneath n c)

/-- Move an explicit disjunction out of n+1 nested existential binders. -/
def extrude : Nat → Certificate
  | 0 => .rule .distributeExists
  | n + 1 => .seq (.under (extrude n)) (.rule .distributeExists)

/-- The same binder permutation and elimination works in BOTH allocation cases.
Binder order: p q r t -> q p r t -> q r p t -> q r t p -> q t r p.
Then eliminate p and r, leaving q and t as the unifier's free parameters. -/
def eliminatePieces : Certificate := steps [
  .rule .exchangeExists,
  beneath 1 (.rule .exchangeExists),
  beneath 2 (.rule .exchangeExists),
  beneath 1 (.rule .exchangeExists),
  beneath 3 (.rule .eliminate),
  beneath 2 (.rule .eliminate)]

/--
One input equation; auxiliary equations only arise from Mutate.

X+Y ≈ atom(7)+Z
  -> ∃ p q r t. X≈p+q ∧ Y≈r+t ∧ atom(7)≈p+r ∧ Z≈q+t
  -> allocation p≈0,r≈atom(7) OR p≈atom(7),r≈0 (both retained)
  -> distribute, replace/eliminate p,r, simplify units
  -> the two solved substitution families shown in the final native theorem.

Only primitive rule data is used; no problem-specific proof occurs here.
-/
def overlapPrimitiveTrace : Certificate := steps [
  .rule .mutate,
  beneath 4 (.right (.right (.left (.seq (.rule .symmetry) (.rule .splitAtom))))),
  beneath 4 (.right (.right (.rule .distributeLeft))),
  beneath 4 (.right (.rule .distributeRight)),
  beneath 4 (.rule .distributeRight),
  extrude 3,
  .left eliminatePieces,
  .right eliminatePieces,
  .rule .swapBranches]

end Certification2.Demo

/-! ## User model: ordinary datatypes and the existing structural declaration -/

namespace Certification2.IndexedExample

inductive Bag where
  | empty | red | blue
  | union : Bag → Bag → Bag
  deriving Repr, DecidableEq

inductive Conf where
  | wrap : Bag → Conf

instance : framework.State Conf := ⟨⟩

open scoped Structural

structural WrappedTheory where
  assoc Bag.union
  comm Bag.union
  id Bag.union Bag.empty

-- One annotation; all constructor metadata and registration proofs are generated.
certify_structural WrappedTheory for Conf

open Structural.Indexed WrappedTheory.Generated

-- Generic checker instantiated with automatically generated metadata.
private abbrev bridge := Wrapper.checker registration code read read_code

/-! ## User-level certificate example

Only native constructor terms in the statement. Inversion of the free wrapper
is a library theorem; after that the SAME primitive ACU certificate is checked.
The explicit `.certified` selects the library's indexed semantics. The existing
`=[WrappedTheory]` retains its original meaning during migration.
-/

theorem wrapped_two_unifiers (X Y Z : Bag) :
    Conf.wrap (Bag.union X Y) =[WrappedTheory.certified] Conf.wrap (Bag.union .red Z) ↔
      (∃ p q : Bag, X =[WrappedTheory.certified] Bag.union .red p ∧
        Y =[WrappedTheory.certified] q ∧ Z =[WrappedTheory.certified] Bag.union p q) ∨
      (∃ p q : Bag, X =[WrappedTheory.certified] p ∧
        Y =[WrappedTheory.certified] Bag.union .red q ∧ Z =[WrappedTheory.certified] Bag.union p q) := by
  refine (Wrapper.native_wrap_iff registration code read read_code _ _).trans ?_
  have certified := bridge.check_exact
    (.eqn (.add (.var 0) (.var 1)) (.add (.atom 0) (.var 2)))
    (overlapSolutions (.var 0) (.var 1) (.var 2) 0)
    Demo.overlapPrimitiveTrace (by decide)
    (by simp [Formula.uses, Term.uses, bridge, Wrapper.checker, code, WrappedTheory.Generated.read])
    (by simp [overlapSolutions, Formula.uses, Term.uses, Term.lift, bridge,
      Wrapper.checker, code, WrappedTheory.Generated.read])
    (fun n => match n with | 0 => X | 1 => Y | _ => Z)
  simpa only [overlapSolutions, Formula.sat, Term.denote, Term.lift] using certified

-- Regression checks: the free wrapper respects ACU but does not collapse atoms.
example (a : Bag) : Conf.wrap (Bag.union a .empty) =[WrappedTheory.certified] Conf.wrap a := by
  apply (Wrapper.native_wrap_iff registration code read read_code _ _).mpr
  apply (Wrapper.exact code read read_code _ _).mpr
  exact .unitRight _

example : ¬ (Conf.wrap Bag.red =[WrappedTheory.certified] Conf.wrap Bag.blue) := by
  intro h
  have hp := ((Wrapper.exact code read read_code _ _).mp h).flatten_perm
  change ([0] : List Nat).Perm [1] at hp
  simp at hp

#print axioms wrapped_two_unifiers

-- Certified equality still provides ordinary EqMod evidence to existing clients.
example {a b : Conf} (h : a =[WrappedTheory.certified] b) : a =[WrappedTheory] b :=
  Structural.CertifiedTheory.to_original WrappedTheory.certified h

end Certification2.IndexedExample

/-! Registration regression: different names, three atoms, and an atom declared
after the binary constructor. No generated declarations are supplied by hand. -/
namespace Certification2.RegistrationRegression

inductive Contents where
  | nothing | apple
  | combine : Contents → Contents → Contents
  | pear | plum

inductive State where
  | box : Contents → State

instance : framework.State State := ⟨⟩

open scoped Structural

structural FruitTheory where
  comm Contents.combine
  id Contents.combine Contents.nothing
  assoc Contents.combine

certify_structural FruitTheory for State

example (x : Contents) :
    State.box (Contents.combine x .nothing) =[FruitTheory.certified] State.box x := by
  apply (Structural.Indexed.Wrapper.native_wrap_iff FruitTheory.Generated.registration
    FruitTheory.Generated.code FruitTheory.Generated.read FruitTheory.Generated.read_code _ _).mpr
  exact Structural.Indexed.Eq.trans
    (Structural.Indexed.Eq.comm (sig := FruitTheory.Generated.Sig)
      Structural.Indexed.Wrapper.Operator.union _ _)
    (Structural.Indexed.Eq.unit (sig := FruitTheory.Generated.Sig)
      Structural.Indexed.Wrapper.Operator.union _)

-- Unsupported signatures fail at validation, before any metadata is generated.
inductive NotAWrapper where
  | first | second

/-- error: certify_structural currently requires one free unary state constructor -/
#guard_msgs in
certify_structural FruitTheory for NotAWrapper

end Certification2.RegistrationRegression

/-! ## Internal regression checks (not additional user proof obligations) -/

namespace Certification2.Regression

abbrev F := Formula Structural.Indexed.Wrapper.SortTag.bag

-- A successful derivation cannot certify an answer with one branch omitted.
example : check
    (.eqn (.add (.var 0) (.var 1)) (.add (.atom 0) (.var 2)) : F)
    (.ex (.ex (.conj (.eqn (.var 2) (.add (.atom 0) (.var 1)))
      (.conj (.eqn (.var 3) (.var 0)) (.eqn (.var 4) (.add (.var 1) (.var 0)))))))
    Demo.overlapPrimitiveTrace = false := by decide

-- Elimination refuses a replacement mentioning the binder being removed.
example : check
    (.ex (.conj (.eqn (.var 0) (.add (.var 0) (.atom 0))) .truth) : F)
    .truth (.rule .eliminate) = false := by decide

-- Substitution lifts through inner binders; it never captures the outer y.
-- ∃x. x≈y ∧ (∃z. x≈z) -> ∃z. y≈z, not ∃z. z≈z.
example : check
    (.ex (.conj (.eqn (.var 0) (.var 1)) (.ex (.eqn (.var 1) (.var 0)))) : F)
    (.ex (.eqn (.var 1) (.var 0))) (Demo.steps [.rule .eliminate]) = true := by decide
example : check
    (.ex (.conj (.eqn (.var 0) (.var 1)) (.ex (.eqn (.var 1) (.var 0)))) : F)
    (.ex (.eqn (.var 0) (.var 0))) (Demo.steps [.rule .eliminate]) = false := by decide

-- ACU does not permit an ordinary syntactic occurs-check failure: X+Y≈X iff Y≈0.
example : check (.eqn (.add (.var 0) (.var 1)) (.var 0) : F)
    (.eqn (.var 1) .zero)
    (.seq (.rule .commLeft) (.seq (.rule .padRight) (.rule .cancel))) = true := by decide

end Certification2.Regression

/-! ## Small certificates against the actual Bakery model

These use the existing BakeryTheory/EqMod, not a renamed copy of the model or
the restricted `.certified` wrapper demo. They exercise the normalization and
variable-solving fragment only: no cancellation, constructor inversion, ACU
splitting, narrowing, or Maude search is claimed here.

The general rules below preserve the ENTIRE solution set (an iff). They require
only equivalence of structural equality, so they need no native reflection
registration. Stronger decomposition/splitting rules still require that bridge.
-/

namespace Certification2.NativeRules

open Structural

universe u
variable {B : Structural.Theory.{u}} {α : Type u}

/-- Normalize: l =B l', r =B r' ⇒ (l =B r ↔ l' =B r').
Both implications are proved, not merely soundness of a proposed answer. -/
theorem normalize {l l' r r' : α} (hl : EqMod B l l') (hr : EqMod B r r') :
    EqMod B l r ↔ EqMod B l' r' :=
  ⟨fun h => .trans (.symm hl) (.trans h hr),
   fun h => .trans hl (.trans h (.symm hr))⟩

/-- Solve X =B Y with the substitution family {X ↦ U, Y ↦ U}.
Assignments factor modulo B, not by literal equality of raw syntax. -/
theorem shared {x y : α} :
    EqMod B x y ↔ ∃ v : α, EqMod B x v ∧ EqMod B y v :=
  ⟨fun h => ⟨y, h, .ofEq rfl⟩, fun ⟨_, hx, hy⟩ => .trans hx (.symm hy)⟩

end Certification2.NativeRules

namespace Certification2.BakeryExamples

open Structural ProcSet Mode

-- Input: X + empty =B {idle}.
-- Complete answer: one substitution X ↦ {idle}, modulo B.
-- Certification: normalize the unit; the remaining equation IS the answer.
theorem idle_unifier (X : ProcSet) :
    union X empty =[BakeryTheory] singleton idle ↔
      X =[BakeryTheory] singleton idle := by
  exact NativeRules.normalize (.identityRight union empty X) (.ofEq rfl)

-- Input: empty + (X + empty) =B Y + empty.
-- Complete answer: one family {X ↦ U, Y ↦ U}; U is an arbitrary process set.
-- Certification: normalize both sides, then apply the generic variable rule.
theorem shared_process_unifier (X Y : ProcSet) :
    union empty (union X empty) =[BakeryTheory] union Y empty ↔
      ∃ U : ProcSet, X =[BakeryTheory] U ∧ Y =[BakeryTheory] U := by
  refine (NativeRules.normalize
    (.trans (.identityLeft union empty _) (.identityRight union empty X))
    (.identityRight union empty Y)).trans ?_
  exact NativeRules.shared

-- Input is a configuration equation, with one unknown complete state C.
-- Parameters n,s,P stay fixed. The answer assigns C the normalized state.
-- Congruence carries the registered unit law through the real Conf constructor;
-- no assumption of injectivity modulo B or special Bakery proof rule is used.
theorem configuration_unifier (n s : Nat) (P : ProcSet) (C : Conf) :
    C =[BakeryTheory] Conf.mk n s (union P empty) ↔
      C =[BakeryTheory] Conf.mk n s P := by
  apply NativeRules.normalize (.ofEq rfl)
  exact .constructor
    (.app (.app (.app (.head Conf.mk) (.ofEq rfl)) (.ofEq rfl))
      (.identityRight union empty P))

#print axioms idle_unifier
#print axioms shared_process_unifier
#print axioms configuration_unifier

end Certification2.BakeryExamples
