import Std

/-!
# Portable, rule-based ACU certificates (standalone experiment)

References:
* A. Boudet and E. Contejean, "Syntactic" AC-Unification, CCL 1994,
  pp. 136--151, https://doi.org/10.1007/BFb0016849
  Author copy: https://www.lri.fr/~contejea/publis/1994ccl/main.pdf
  Definition 4: a complete set of solved forms is an EXACT disjunction.
  Section 2.2 / Figure 1: Mutate replaces an equation using the complete
  solutions of a generic head equation; contextual replacement composes steps.
  The paper proves an AC algorithm. Our ACU specialization below is proved here;
  its termination/pruning results are NOT imported as results about ACU.
* J.-P. Jouannaud and C. Kirchner, Solving equations in abstract algebras:
  A rule-based survey of unification, Computational Logic, MIT Press, 1991.

Scope: one free ACU component at a time, with distinct sort tags and numbered
atomic constants. A component can be placed at ANY sort; this is not a Bakery
signature. Mixed-sort free-constructor applications and a complete search
strategy for nonlinear problems are future work.

The certificate is ordinary first-order DATA. Maude can emit its rule tags and
tree structure. Lean reconstructs proofs of individual steps. There is no
Diophantine solver, arbitrary Lean proof field, or per-problem lemma in a trace.
Lists occur only in the GENERAL semantic proof that the free ACU relation has
the required decomposition properties. The checker never searches lists/bags.

Integration boundary: `ACU` below is explicitly sort-indexed. It is the local
free-ACU semantics, not an alias for the library's `Structural.EqMod`. Connecting
native registered datatypes to this semantics still requires a faithful bridge.
This file does not assume that bridge, or change the library relation.

Next integration experiment (before automatic model export): use ONE native,
registered datatype with a free ACU constructor and nullary atom constructors.
Use a signature-restricted atom alphabet (or well-formedness predicate), not
arbitrary Nat codes for symbols absent from that native signature. Prove
encode/decode round trips modulo the respective relations on that fragment, and

  Structural.EqMod B a b  <->  ACU (encode a) (encode b).

Decoding an ACU derivation only requires the registered laws (soundness).
The reverse direction must account for EVERY generator of native EqMod,
including constructor congruence and registrations at other Lean types. Sort
tags in THIS syntax alone do not discharge that reflection obligation for the
existing library relation. Do not mark the native bridge complete after proving
only preservation. Mixed-sort constructors such as Bakery's follow this test;
numbered constants alone do not yet model their arguments or nested theories.
-/

namespace Certification2

/-! ## General semantic metatheorems (not problem certificates) -/

/-- Ground terms of one ACU component. `s` is a genuine type index. -/
inductive Value {Sorts : Type} (s : Sorts) where
  | zero
  | atom (symbol : Nat)
  | add (left right : Value s)
  deriving Repr, DecidableEq

variable {Sorts : Type} {s : Sorts}

/-- Exactly the congruence generated by ACU, with no extra algebraic laws. -/
inductive ACU : Value s → Value s → Prop where
  | refl (a) : ACU a a
  | symm {a b} : ACU a b → ACU b a
  | trans {a b c} : ACU a b → ACU b c → ACU a c
  | congr {a b c d} : ACU a b → ACU c d → ACU (.add a c) (.add b d)
  | assoc (a b c) : ACU (.add (.add a b) c) (.add a (.add b c))
  | comm (a b) : ACU (.add a b) (.add b a)
  | unit (a) : ACU (.add .zero a) a

namespace Value

def flatten : Value s → List Nat
  | .zero => []
  | .atom a => [a]
  | .add a b => a.flatten ++ b.flatten

def ofList : List Nat → Value s
  | [] => .zero
  | a :: as => .add (.atom a) (ofList as)

@[simp] theorem flatten_ofList (xs : List Nat) :
    (ofList (s := s) xs).flatten = xs := by
  induction xs with
  | nil => rfl
  | cons a as ih => simp [ofList, flatten, ih]

end Value

namespace ACU

theorem unitRight (a : Value s) : ACU (.add a .zero) a :=
  (comm _ _).trans (unit _)

theorem exchange (a b c : Value s) :
    ACU (.add a (.add b c)) (.add b (.add a c)) :=
  (assoc _ _ _).symm.trans ((congr (comm _ _) (refl _)).trans (assoc _ _ _))

theorem flatten_perm {a b : Value s} (h : ACU a b) :
    a.flatten.Perm b.flatten := by
  induction h with
  | refl => exact .refl _
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | congr _ _ ih₁ ih₂ => exact ih₁.append ih₂
  | assoc => simp [Value.flatten, List.append_assoc]
  | comm => exact List.perm_append_comm
  | unit => exact .refl _

theorem ofList_append (xs ys : List Nat) :
    ACU (Value.ofList (s := s) (xs ++ ys))
      (.add (Value.ofList xs) (Value.ofList ys)) := by
  induction xs with
  | nil => exact (unit _).symm
  | cons a as ih =>
      exact (congr (refl _) ih).trans (assoc _ _ _).symm

theorem normalize (a : Value s) : ACU a (Value.ofList a.flatten) := by
  induction a with
  | zero => exact refl _
  | atom => exact (unitRight _).symm
  | add a b ih₁ ih₂ =>
      exact (congr ih₁ ih₂).trans (ofList_append _ _).symm

theorem ofList_perm {xs ys : List Nat} (h : xs.Perm ys) :
    ACU (Value.ofList (s := s) xs) (Value.ofList ys) := by
  induction h with
  | nil => exact refl _
  | cons a _ ih => exact congr (refl _) ih
  | swap => exact exchange _ _ _
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Faithfulness is proved, rather than assumed as a model registration field. -/
theorem iff_perm (a b : Value s) : ACU a b ↔ a.flatten.Perm b.flatten :=
  ⟨flatten_perm, fun h => (normalize a).trans ((ofList_perm h).trans (normalize b).symm)⟩

theorem cancel (a b c : Value s) :
    ACU (.add a c) (.add b c) ↔ ACU a b := by
  simp only [iff_perm, Value.flatten, List.perm_append_right_iff]

theorem split_zero (a b : Value s) :
    ACU (.add a b) .zero ↔ ACU a .zero ∧ ACU b .zero := by
  simp [iff_perm, Value.flatten]

theorem split_atom (a b : Value s) (k : Nat) :
    ACU (.add a b) (.atom k) ↔
      (ACU a .zero ∧ ACU b (.atom k)) ∨
      (ACU a (.atom k) ∧ ACU b .zero) := by
  simp only [iff_perm, Value.flatten, List.perm_nil, List.perm_singleton]
  cases ha : a.flatten with
  | nil => simp
  | cons x xs =>
      cases hb : b.flatten with
      | nil => simp
      | cons y ys => simp

end ACU

/-- General refinement of four bags; auxiliary to the ACU Mutate theorem. -/
theorem perm_refine {α : Type} (a b c d : List α)
    (h : (a ++ b).Perm (c ++ d)) :
    ∃ p q r t, a.Perm (p ++ q) ∧ b.Perm (r ++ t) ∧
      c.Perm (p ++ r) ∧ d.Perm (q ++ t) := by
  induction a generalizing c d with
  | nil => exact ⟨[], [], c, d, .refl _, h, .refl _, .refl _⟩
  | cons x a ih =>
      have hm : x ∈ c ++ d := h.mem_iff.mp (by simp)
      rcases List.mem_append.mp hm with hc | hd
      · rcases List.mem_iff_append.mp hc with ⟨l, r, rfl⟩
        have hp : (l ++ x :: r ++ d).Perm (x :: ((l ++ r) ++ d)) := by
          simpa only [List.cons_append] using
            (List.perm_middle (a := x) (l₁ := l) (l₂ := r)).append_right d
        obtain ⟨p, q, r', t, ha, hb, hc, hd⟩ := ih (l ++ r) d (h.trans hp).cons_inv
        exact ⟨x :: p, q, r', t, ha.cons x, hb,
          List.perm_middle.trans (hc.cons x), hd⟩
      · rcases List.mem_iff_append.mp hd with ⟨l, r, rfl⟩
        have hp : (c ++ (l ++ x :: r)).Perm (x :: (c ++ (l ++ r))) := by
          exact ((List.perm_middle (a := x) (l₁ := l) (l₂ := r)).append_left c).trans
            List.perm_middle
        obtain ⟨p, q, r', t, ha, hb, hc, hd⟩ := ih c (l ++ r) (h.trans hp).cons_inv
        exact ⟨p, x :: q, r', t, (ha.cons x).trans List.perm_middle.symm,
          hb, hc, List.perm_middle.trans (hd.cons x)⟩

/--
ACU specialization of Mutate for the generic head equation x+y = u+v.
Empty pieces subsume the smaller overlap shapes needed in AC without a unit.

  a+b ≈ c+d
  ----------------------------------------------------- [MutateACU]
  ∃ p q r t, a≈p+q ∧ b≈r+t ∧ c≈p+r ∧ d≈q+t

The equivalence proves BOTH completeness and soundness of this rule.
-/
theorem ACU.mutate (a b c d : Value s) :
    ACU (.add a b) (.add c d) ↔
      ∃ p q r t, ACU a (.add p q) ∧ ACU b (.add r t) ∧
        ACU c (.add p r) ∧ ACU d (.add q t) := by
  constructor
  · intro h
    obtain ⟨p, q, r, t, ha, hb, hc, hd⟩ :=
      perm_refine a.flatten b.flatten c.flatten d.flatten h.flatten_perm
    refine ⟨Value.ofList p, Value.ofList q, Value.ofList r, Value.ofList t, ?_⟩
    simpa only [ACU.iff_perm, Value.flatten, Value.flatten_ofList] using ⟨ha, hb, hc, hd⟩
  · rintro ⟨p, q, r, t, ha, hb, hc, hd⟩
    have middle : ACU (.add (.add p q) (.add r t)) (.add (.add p r) (.add q t)) :=
      (ACU.assoc _ _ _).trans
        ((ACU.congr (ACU.refl _) (ACU.exchange _ _ _)).trans (ACU.assoc _ _ _).symm)
    exact (ACU.congr ha hb).trans (middle.trans (ACU.congr hc hd).symm)

/--
Derived ACU rule: compose Mutate with atom splitting and unit elimination.
This is a reusable rule schema, not a new completeness assumption or a rule
claimed to occur verbatim in BC94. Its proof expands to the general rules above.
The two alternatives account for which summand contains the distinguished atom;
the remaining pieces are arbitrary, and can overlap or be empty.
-/
theorem ACU.peel_atom (a b c : Value s) (k : Nat) :
    ACU (.add a b) (.add (.atom k) c) ↔
      (∃ p q, ACU a (.add (.atom k) p) ∧ ACU b q ∧ ACU c (.add p q)) ∨
      (∃ p q, ACU a p ∧ ACU b (.add (.atom k) q) ∧ ACU c (.add p q)) := by
  constructor
  · intro h
    obtain ⟨p, q, r, t, ha, hb, hk, hc⟩ := (ACU.mutate _ _ _ _).mp h
    rcases (ACU.split_atom p r k).mp hk.symm with ⟨hp, hr⟩ | ⟨hp, hr⟩
    · exact Or.inr ⟨q, t, ha.trans ((ACU.congr hp (.refl q)).trans (ACU.unit q)),
        hb.trans (ACU.congr hr (.refl t)), hc⟩
    · exact Or.inl ⟨q, t, ha.trans (ACU.congr hp (.refl q)),
        hb.trans ((ACU.congr hr (.refl t)).trans (ACU.unit t)), hc⟩
  · rintro (⟨p, q, ha, hb, hc⟩ | ⟨p, q, ha, hb, hc⟩)
    · exact (ACU.congr ha hb).trans
        ((ACU.assoc _ _ _).trans (ACU.congr (.refl _) hc.symm))
    · exact (ACU.congr ha hb).trans
        ((ACU.exchange _ _ _).trans (ACU.congr (.refl _) hc.symm))

/-! ## Portable syntax and certificate format -/

/-- Variables and atom symbols have separate namespaces. -/
inductive Term {Sorts : Type} (s : Sorts) where
  | var (index : Nat)
  | atom (symbol : Nat)
  | zero
  | add (left right : Term s)
  deriving Repr, DecidableEq

abbrev Assignment (s : Sorts) := Nat → Value s

def push (v : Value s) (ρ : Assignment s) : Assignment s
  | 0 => v
  | n + 1 => ρ n

namespace Term

def eval : Term s → Assignment s → Value s
  | .var n, ρ => ρ n
  | .atom k, _ => .atom k
  | .zero, _ => .zero
  | .add a b, ρ => .add (a.eval ρ) (b.eval ρ)

/-- De Bruijn lifting prevents capture when Mutate introduces witnesses. -/
def lift : Term s → Term s
  | .var n => .var (n + 1)
  | .atom k => .atom k
  | .zero => .zero
  | .add a b => .add a.lift b.lift

@[simp] theorem eval_lift (a : Term s) (v : Value s) (ρ : Assignment s) :
    a.lift.eval (push v ρ) = a.eval ρ := by
  induction a with
  | var => rfl
  | atom => rfl
  | zero => rfl
  | add a b ih₁ ih₂ => simp only [lift, eval, ih₁, ih₂]

end Term

/-- Explicit formulas, not arbitrary Lean propositions or closures. -/
inductive Formula {Sorts : Type} (s : Sorts) where
  | truth
  | falsity
  | eqn (left right : Term s)
  | conj (left right : Formula s)
  | disj (left right : Formula s)
  | ex (body : Formula s)
  deriving Repr, DecidableEq

def Formula.Holds : Formula s → Assignment s → Prop
  | .truth, _ => True
  | .falsity, _ => False
  | .eqn a b, ρ => ACU (a.eval ρ) (b.eval ρ)
  | .conj p q, ρ => p.Holds ρ ∧ q.Holds ρ
  | .disj p q, ρ => p.Holds ρ ∨ q.Holds ρ
  | .ex p, ρ => ∃ v, p.Holds (push v ρ)

def Equivalent (p q : Formula s) : Prop := ∀ ρ, p.Holds ρ ↔ q.Holds ρ

/-! ### Capture-avoiding replacement and existential elimination

Var-Rep / EQE, specialized to our explicit binder syntax:

    ∃ x. (x ≈ t ∧ P)    <=>    P[t/x]       (x not free in t)

This is replacement MODULO ACU, not replacement by literal Lean equality.
`Holds_congr` is essential: every formula in this calculus respects ACU in
its variable assignments. This does not assert that arbitrary user constraints
have that property. Substitution under a binder lifts the replacement terms.
-/

def Term.subst (σ : Nat → Term s) : Term s → Term s
  | .var n => σ n
  | .atom k => .atom k
  | .zero => .zero
  | .add a b => .add (a.subst σ) (b.subst σ)

theorem Term.eval_subst (a : Term s) (σ : Nat → Term s) (ρ : Assignment s) :
    (a.subst σ).eval ρ = a.eval (fun n => (σ n).eval ρ) := by
  induction a <;> simp_all [subst, eval]

def upSubst (σ : Nat → Term s) : Nat → Term s
  | 0 => .var 0
  | n + 1 => (σ n).lift

def Formula.subst (σ : Nat → Term s) : Formula s → Formula s
  | .truth => .truth
  | .falsity => .falsity
  | .eqn a b => .eqn (a.subst σ) (b.subst σ)
  | .conj p q => .conj (p.subst σ) (q.subst σ)
  | .disj p q => .disj (p.subst σ) (q.subst σ)
  | .ex p => .ex (p.subst (upSubst σ))

theorem Formula.holds_subst (p : Formula s) (σ : Nat → Term s) (ρ : Assignment s) :
    (p.subst σ).Holds ρ ↔ p.Holds (fun n => (σ n).eval ρ) := by
  induction p generalizing σ ρ with
  | truth => rfl
  | falsity => rfl
  | eqn => simp only [subst, Holds, Term.eval_subst]
  | conj p q hp hq => exact and_congr (hp σ ρ) (hq σ ρ)
  | disj p q hp hq => exact or_congr (hp σ ρ) (hq σ ρ)
  | ex p hp =>
      apply exists_congr
      intro v
      have he : (fun n => (upSubst σ n).eval (push v ρ)) =
          push v (fun n => (σ n).eval ρ) := by
        funext n
        cases n <;> simp [upSubst, push, Term.eval]
      exact (hp _ _).trans (he ▸ Iff.rfl)

theorem Term.eval_congr (a : Term s) {ρ τ : Assignment s}
    (h : ∀ n, ACU (ρ n) (τ n)) : ACU (a.eval ρ) (a.eval τ) := by
  induction a with
  | var n => exact h n
  | atom => exact .refl _
  | zero => exact .refl _
  | add a b ha hb => exact .congr ha hb

theorem Formula.holds_congr (p : Formula s) {ρ τ : Assignment s}
    (h : ∀ n, ACU (ρ n) (τ n)) : p.Holds ρ ↔ p.Holds τ := by
  induction p generalizing ρ τ with
  | truth => rfl
  | falsity => rfl
  | eqn a b => exact
      ⟨fun e => (a.eval_congr h).symm.trans (e.trans (b.eval_congr h)),
       fun e => (a.eval_congr h).trans (e.trans (b.eval_congr h).symm)⟩
  | conj p q hp hq => exact and_congr (hp h) (hq h)
  | disj p q hp hq => exact or_congr (hp h) (hq h)
  | ex p hp =>
      apply exists_congr
      intro v
      apply hp
      intro n
      cases n with
      | zero => exact .refl _
      | succ n => exact h n

/-- Inverse of lift, undefined if the term mentions the variable being removed. -/
def Term.lower : Term s → Option (Term s)
  | .var 0 => none
  | .var (n + 1) => some (.var n)
  | .atom k => some (.atom k)
  | .zero => some .zero
  | .add a b => return .add (← a.lower) (← b.lower)

theorem Term.lower_lift {a t : Term s} (h : a.lower = some t) : a = t.lift := by
  induction a generalizing t with
  | var n =>
      cases n with
      | zero => simp [lower] at h
      | succ n => cases Option.some.inj h; rfl
  | atom => cases Option.some.inj h; rfl
  | zero => cases Option.some.inj h; rfl
  | add a b ha hb =>
      cases he₁ : a.lower <;> cases he₂ : b.lower <;> simp [lower, he₁, he₂] at h
      cases h
      simp only [lift, ha he₁, hb he₂]

def replaceZero (t : Term s) : Nat → Term s
  | 0 => t
  | n + 1 => .var n

theorem eliminate_correct (t : Term s) (p : Formula s) :
    Equivalent (.ex (.conj (.eqn (.var 0) t.lift) p))
      (p.subst (replaceZero t)) := by
  intro ρ
  rw [Formula.holds_subst]
  have he : (fun n => (replaceZero t n).eval ρ) = push (t.eval ρ) ρ := by
    funext n
    cases n <;> rfl
  rw [he]
  change (∃ v, ACU v (t.lift.eval (push v ρ)) ∧ p.Holds (push v ρ)) ↔ _
  simp only [Term.eval_lift]
  constructor
  · rintro ⟨v, hv, hp⟩
    apply (p.holds_congr (ρ := push v ρ) (τ := push (t.eval ρ) ρ) ?_).mp hp
    intro n
    cases n with
    | zero => exact hv
    | succ => exact .refl _
  · intro hp
    exact ⟨t.eval ρ, .refl _, hp⟩

/-- Move a binding to the front of a conjunction tree, retaining every sibling.
No disjunction is crossed. The returned term is already lowered/freshness-checked. -/
def binding (p : Formula s) :
    Option { pair : Term s × Formula s //
      Equivalent p (.conj (.eqn (.var 0) pair.1.lift) pair.2) } :=
  match p with
  | .eqn (.var 0) t => do
      let u ← t.lower.attach
      return ⟨(u.val, .truth), by
        have ht := Term.lower_lift u.property
        intro ρ
        change ACU (ρ 0) (t.eval ρ) ↔ ACU (ρ 0) (u.val.lift.eval ρ) ∧ True
        simp only [ht, and_true]⟩
  | .conj p q =>
      match binding p with
      | some ⟨(t, p'), h⟩ => some ⟨(t, .conj p' q), fun ρ => by
          change p.Holds ρ ∧ q.Holds ρ ↔ _
          rw [h ρ]
          exact and_assoc⟩
      | none => do
          let ⟨(t, q'), h⟩ ← binding q
          return ⟨(t, .conj p q'), fun ρ => by
            change p.Holds ρ ∧ q.Holds ρ ↔ _
            rw [h ρ]
            exact and_left_comm⟩
  | _ => none

def swapZeroOne : Nat → Term s
  | 0 => .var 1
  | 1 => .var 0
  | n + 2 => .var (n + 2)

theorem exchange_exists_correct (p : Formula s) :
    Equivalent (.ex (.ex p)) (.ex (.ex (p.subst swapZeroOne))) := by
  intro ρ
  have he (v w : Value s) :
      (fun n => (swapZeroOne n).eval (push w (push v ρ))) = push v (push w ρ) := by
    funext n
    cases n with
    | zero => rfl
    | succ n => cases n <;> rfl
  change (∃ v w, p.Holds (push w (push v ρ))) ↔ _
  simp only [Formula.Holds, Formula.holds_subst, he]
  exact exists_comm

/-- Only unit simplification, not ACU unification or matching. -/
def Term.units : (a : Term s) → { b : Term s // ∀ ρ, ACU (a.eval ρ) (b.eval ρ) }
  | .add a b =>
      let ⟨a', ha⟩ := a.units
      let ⟨b', hb⟩ := b.units
      match a', b' with
      | .zero, b' => ⟨b', fun ρ => (ACU.congr (ha ρ) (hb ρ)).trans (ACU.unit _)⟩
      | a', .zero => ⟨a', fun ρ => (ACU.congr (ha ρ) (hb ρ)).trans (ACU.unitRight _)⟩
      | a', b' => ⟨.add a' b', fun ρ => ACU.congr (ha ρ) (hb ρ)⟩
  | .zero => ⟨.zero, fun _ => .refl _⟩
  | .var n => ⟨.var n, fun _ => .refl _⟩
  | .atom k => ⟨.atom k, fun _ => .refl _⟩

/-- Deterministic cleanup: remove units in terms and True conjuncts in formulas.
It neither deletes alternatives nor decides satisfiability. -/
def Formula.cleanup : (p : Formula s) → { q : Formula s // Equivalent p q }
  | .eqn a b =>
      let ⟨a', ha⟩ := a.units
      let ⟨b', hb⟩ := b.units
      ⟨.eqn a' b', fun ρ =>
        ⟨fun h => (ha ρ).symm.trans (h.trans (hb ρ)),
         fun h => (ha ρ).trans (h.trans (hb ρ).symm)⟩⟩
  | .conj p q =>
      let ⟨p', hp⟩ := p.cleanup
      let ⟨q', hq⟩ := q.cleanup
      match p', q' with
      | .truth, q' => ⟨q', fun ρ => (and_congr (hp ρ) (hq ρ)).trans (by
          simp only [Holds, true_and])⟩
      | p', .truth => ⟨p', fun ρ => (and_congr (hp ρ) (hq ρ)).trans (by
          simp only [Holds, and_true])⟩
      | p', q' => ⟨.conj p' q', fun ρ => and_congr (hp ρ) (hq ρ)⟩
  | .disj p q =>
      let ⟨p', hp⟩ := p.cleanup
      let ⟨q', hq⟩ := q.cleanup
      ⟨.disj p' q', fun ρ => or_congr (hp ρ) (hq ρ)⟩
  | .ex p =>
      let ⟨p', hp⟩ := p.cleanup
      ⟨.ex p', fun ρ => exists_congr (fun v => hp (push v ρ))⟩
  | .truth => ⟨.truth, fun _ => Iff.rfl⟩
  | .falsity => ⟨.falsity, fun _ => Iff.rfl⟩

/-- Every rule has a finite, explicit output, including ALL alternatives. -/
inductive Rule where
  | mutate | splitAtom | splitZero | cancel | peelAtom
  | symmetry | commLeft | assocLeft | padRight
  | reflexive | clash
  | distributeLeft | distributeRight
  | eliminate | exchangeExists | distributeExists
  | cleanup | swapBranches
  deriving Repr, DecidableEq

/--
This is the external certificate format. No fields contain Lean proofs/functions.
`left`/`right` select a logical conjunct/disjunct, `under` enters an existential.
Maude can mirror these constructors directly. Term/equation positions are explicit
in the tree; no matching modulo ACU is performed during replay.
-/
inductive Certificate where
  | rule (tag : Rule)
  | seq (first second : Certificate)
  | left (proof : Certificate)
  | right (proof : Certificate)
  | under (proof : Certificate)
  deriving Repr, DecidableEq

/-- Four fresh variables are indices 3,2,1,0 after four nested binders. -/
def mutation (a b c d : Term s) : Formula s :=
  .ex (.ex (.ex (.ex (
    .conj (.eqn a.lift.lift.lift.lift (.add (.var 3) (.var 2)))
    (.conj (.eqn b.lift.lift.lift.lift (.add (.var 1) (.var 0)))
    (.conj (.eqn c.lift.lift.lift.lift (.add (.var 3) (.var 1)))
           (.eqn d.lift.lift.lift.lift (.add (.var 2) (.var 0)))))))))

theorem mutation_correct (a b c d : Term s) :
    Equivalent (.eqn (.add a b) (.add c d)) (mutation a b c d) := by
  intro ρ
  simp only [mutation, Formula.Holds, Term.eval_lift, Term.eval, push]
  exact ACU.mutate _ _ _ _

/-- Output of the derived rule, with two independently scoped parameter pairs. -/
def peel (a b c : Term s) (k : Nat) : Formula s :=
  .disj
    (.ex (.ex (.conj (.eqn a.lift.lift (.add (.atom k) (.var 1)))
      (.conj (.eqn b.lift.lift (.var 0)) (.eqn c.lift.lift (.add (.var 1) (.var 0)))))))
    (.ex (.ex (.conj (.eqn a.lift.lift (.var 1))
      (.conj (.eqn b.lift.lift (.add (.atom k) (.var 0)))
        (.eqn c.lift.lift (.add (.var 1) (.var 0)))))))

theorem peel_correct (a b c : Term s) (k : Nat) :
    Equivalent (.eqn (.add a b) (.add (.atom k) c)) (peel a b c k) := by
  intro ρ
  simp only [peel, Formula.Holds, Term.eval_lift, Term.eval, push]
  exact ACU.peel_atom _ _ _ _

/-! ## Generic proof reconstruction: all reasoning stays in this section -/

variable [DecidableEq Sorts]

/--
A proof-producing local checker. The result carries a Lean proof, but the INPUT
certificate does not. Proof fields erase at execution; the computational work
is constructor inspection and syntactic equality, never unification search.
-/
def applyRule (rule : Rule) (input : Formula s) :
    Option { output : Formula s // Equivalent input output } :=
  match rule, input with
  | .cleanup, p => some p.cleanup
  | .swapBranches, .disj p q => some ⟨.disj q p, fun _ => or_comm⟩
  | .eliminate, .ex p => do
      let ⟨(t, rest), h⟩ ← binding p
      return ⟨rest.subst (replaceZero t), fun ρ =>
        (exists_congr (fun v => h (push v ρ))).trans (eliminate_correct t rest ρ)⟩
  | .exchangeExists, .ex (.ex p) =>
      some ⟨.ex (.ex (p.subst swapZeroOne)), exchange_exists_correct p⟩
  | .distributeExists, .ex (.disj p q) =>
      some ⟨.disj (.ex p) (.ex q), fun _ => exists_or⟩
  | .mutate, .eqn (.add a b) (.add c d) =>
      some ⟨mutation a b c d, mutation_correct a b c d⟩
  | .peelAtom, .eqn (.add a b) (.add (.atom k) c) =>
      some ⟨peel a b c k, peel_correct a b c k⟩
  | .splitAtom, .eqn (.add a b) (.atom k) =>
      some ⟨.disj (.conj (.eqn a .zero) (.eqn b (.atom k)))
                  (.conj (.eqn a (.atom k)) (.eqn b .zero)),
        fun ρ => ACU.split_atom (a.eval ρ) (b.eval ρ) k⟩
  | .splitZero, .eqn (.add a b) .zero =>
      some ⟨.conj (.eqn a .zero) (.eqn b .zero),
        fun ρ => ACU.split_zero (a.eval ρ) (b.eval ρ)⟩
  | .cancel, .eqn (.add a c) (.add b d) =>
      if h : c = d then
        some ⟨.eqn a b, by subst d; exact fun ρ => ACU.cancel _ _ _⟩
      else none
  | .symmetry, .eqn a b =>
      some ⟨.eqn b a, fun _ => ⟨ACU.symm, ACU.symm⟩⟩
  | .commLeft, .eqn (.add a b) c =>
      some ⟨.eqn (.add b a) c, fun _ =>
        ⟨fun h => (ACU.comm _ _).trans h, fun h => (ACU.comm _ _).trans h⟩⟩
  | .assocLeft, .eqn (.add (.add a b) c) d =>
      some ⟨.eqn (.add a (.add b c)) d, fun _ =>
        ⟨fun h => (ACU.assoc _ _ _).symm.trans h,
         fun h => (ACU.assoc _ _ _).trans h⟩⟩
  | .padRight, .eqn a b =>
      some ⟨.eqn a (.add .zero b), fun _ =>
        ⟨fun h => h.trans (ACU.unit _).symm, fun h => h.trans (ACU.unit _)⟩⟩
  | .reflexive, .eqn a b =>
      if h : a = b then
        some ⟨.truth, by subst b; exact fun _ => ⟨fun _ => trivial, fun _ => .refl _⟩⟩
      else none
  | .clash, .eqn (.atom a) (.atom b) =>
      if h : a = b then none
      else some ⟨.falsity, fun _ => ⟨fun hab => h (by
        simpa only [Term.eval, Value.flatten, List.singleton_perm_singleton] using hab.flatten_perm),
        False.elim⟩⟩
  | .distributeLeft, .conj (.disj p q) r =>
      some ⟨.disj (.conj p r) (.conj q r), by
        intro ρ
        change (p.Holds ρ ∨ q.Holds ρ) ∧ r.Holds ρ ↔ _
        constructor
        · rintro ⟨hp | hq, hr⟩
          · exact Or.inl ⟨hp, hr⟩
          · exact Or.inr ⟨hq, hr⟩
        · rintro (⟨hp, hr⟩ | ⟨hq, hr⟩)
          · exact ⟨Or.inl hp, hr⟩
          · exact ⟨Or.inr hq, hr⟩⟩
  | .distributeRight, .conj p (.disj q r) =>
      some ⟨.disj (.conj p q) (.conj p r), by
        intro ρ
        change p.Holds ρ ∧ (q.Holds ρ ∨ r.Holds ρ) ↔ _
        constructor
        · rintro ⟨hp, hq | hr⟩
          · exact Or.inl ⟨hp, hq⟩
          · exact Or.inr ⟨hp, hr⟩
        · rintro (⟨hp, hq⟩ | ⟨hp, hr⟩)
          · exact ⟨hp, Or.inl hq⟩
          · exact ⟨hp, Or.inr hr⟩⟩
  | _, _ => none

/--
Replay proves EXACT equivalence. In particular `left` and `right` transform a
branch while retaining its sibling; they never select and discard an alternative.
Only a finite certificate is traversed. No claim about complete proof SEARCH or
the termination of an ACU unification algorithm is made by this definition.
-/
def replay (cert : Certificate) (input : Formula s) :
    Option { output : Formula s // Equivalent input output } := do
  match cert with
  | .rule tag => applyRule tag input
  | .seq first second =>
      let ⟨middle, h₁⟩ ← replay first input
      let ⟨output, h₂⟩ ← replay second middle
      return ⟨output, fun ρ => (h₁ ρ).trans (h₂ ρ)⟩
  | .left cert =>
      match input with
      | .conj p q =>
          let ⟨p', h⟩ ← replay cert p
          return ⟨.conj p' q, fun ρ => and_congr (h ρ) Iff.rfl⟩
      | .disj p q =>
          let ⟨p', h⟩ ← replay cert p
          return ⟨.disj p' q, fun ρ => or_congr (h ρ) Iff.rfl⟩
      | _ => none
  | .right cert =>
      match input with
      | .conj p q =>
          let ⟨q', h⟩ ← replay cert q
          return ⟨.conj p q', fun ρ => and_congr Iff.rfl (h ρ)⟩
      | .disj p q =>
          let ⟨q', h⟩ ← replay cert q
          return ⟨.disj p q', fun ρ => or_congr Iff.rfl (h ρ)⟩
      | _ => none
  | .under cert =>
      match input with
      | .ex p =>
          let ⟨p', h⟩ ← replay cert p
          return ⟨.ex p', fun ρ => exists_congr (fun v => h (push v ρ))⟩
      | _ => none

/-- The externally proposed output must match the entire reconstructed output. -/
def check (input output : Formula s) (cert : Certificate) : Bool :=
  match replay cert input with
  | none => false
  | some result => decide (result.val = output)

/-- The only theorem needed by the certification examples below. -/
theorem check_exact (input output : Formula s) (cert : Certificate)
    (accepted : check input output cert = true) : Equivalent input output := by
  cases hr : replay cert input with
  | none => simp [check, hr] at accepted
  | some result =>
      have ho : result.val = output := of_decide_eq_true (by
        simpa only [check, hr] using accepted)
      exact ho ▸ result.property

theorem check_complete (input output : Formula s) (cert : Certificate)
    (accepted : check input output cert = true) (ρ : Assignment s) :
    input.Holds ρ → output.Holds ρ := (check_exact input output cert accepted ρ).mp

theorem check_sound (input output : Formula s) (cert : Certificate)
    (accepted : check input output cert = true) (ρ : Assignment s) :
    output.Holds ρ → input.Holds ρ := (check_exact input output cert accepted ρ).mpr

/-! ## Certification examples: data plus one top-level proof each

The inputs are single equations. Lists of equations/disjunctions occur only as
intermediate formulas. Each theorem below obtains its semantic iff by checking
the supplied trace; there are no example-specific proof lemmas or proof tactics.

`check_exact` is intentionally about a supplied final formula. If that formula
is a disjunction of solved bindings (as below), it certifies the unifier set.
It also supports checking intermediate transformations. It does not claim that
every accepted output is in solved form: `truth`, for example, expresses an
unconstrained identity substitution, and arbitrary intermediate equations remain
possible. The semantic theorem states exactly the output that was checked.
-/

namespace Examples

inductive Kind where
  | tickets | processes
  deriving Repr, DecidableEq

example : Kind.tickets ≠ Kind.processes := by decide

abbrev V := Value Kind.processes
abbrev T := Term Kind.processes
abbrev F := Formula Kind.processes

def x : T := .var 0
def y : T := .var 1
def z : T := .var 2
def w : T := .var 3

local infix:50 " ≈ᵤ " => ACU
local infixl:65 " +ᵤ " => Value.add

/-- Atom 7 is just a symbol identifier; its value is irrelevant to every rule. -/
def twoInput : F := .eqn (.add (.add x y) z) (.add (.atom 7) z)

def twoOutput : F :=
  .disj (.conj (.eqn x .zero) (.eqn y (.atom 7)))
        (.conj (.eqn x (.atom 7)) (.eqn y .zero))

/-- Cancel the common arbitrary bag, then keep BOTH atom-allocation cases. -/
def twoTrace : Certificate := .seq (.rule .cancel) (.rule .splitAtom)

/--
Completeness is the forward implication; soundness is the reverse implication.
Z is unconstrained, so each unifier maps it to an arbitrary parameter.
The proof contains only generic certificate checking and unfolding notation.
-/
theorem two_unifiers (X Y Z : V) :
    (X +ᵤ Y) +ᵤ Z ≈ᵤ Value.atom 7 +ᵤ Z ↔
      (X ≈ᵤ .zero ∧ Y ≈ᵤ .atom 7) ∨ (X ≈ᵤ .atom 7 ∧ Y ≈ᵤ .zero) := by
  have certificate := check_exact twoInput twoOutput twoTrace (by decide)
  exact certificate (fun n => match n with | 0 => X | 1 => Y | _ => Z)

/-- One equation, one parametric unifier with four fresh ACU pieces. -/
def matrixInput : F := .eqn (.add x y) (.add z w)

def matrixOutput : F := mutation x y z w

/--
Here Maude only needs to emit `rule mutate`. The theorem demonstrates that the
fresh variables are real existential binders, disjoint from the original four.
The all-zero choices and all possible overlaps are covered automatically.
-/
theorem shared_pieces (X Y U W : V) :
    X +ᵤ Y ≈ᵤ U +ᵤ W ↔
      ∃ p q r t : V,
        X ≈ᵤ p +ᵤ q ∧ Y ≈ᵤ r +ᵤ t ∧ U ≈ᵤ p +ᵤ r ∧ W ≈ᵤ q +ᵤ t := by
  have certificate := check_exact matrixInput matrixOutput (.rule .mutate) (by decide)
  exact certificate (fun n => match n with | 0 => X | 1 => Y | 2 => U | _ => W)

/-- Two unifiers with SHARED, arbitrary fresh pieces, for one atomic problem. -/
def overlapInput : F := .eqn (.add x y) (.add (.atom 7) z)

def overlapOutput : F := peel x y z 7

/-- Abbreviations for certificate DATA; no new proof rules. Every sequence ends
with deterministic cleanup. `beneath n` specifies an explicit binder depth. -/
def steps : List Certificate → Certificate
  | [] => .rule .cleanup
  | c :: cs => .seq c (steps cs)

def beneath : Nat → Certificate → Certificate
  | 0, c => c
  | n + 1, c => .under (beneath n c)

/-- Move an explicit disjunction out of n+1 nested existential binders. -/
def extrude : Nat → Certificate
  | 0 => .rule .distributeExists
  | n + 1 => .seq (.under (extrude n)) (.rule .distributeExists)

/-- The same binder permutation and elimination works in BOTH allocation cases.
Binder order: p q r t -> q p r t -> q r p t -> q r t p -> q t r p.
Then eliminate p and r, leaving q and t as the unifier's free parameters. -/
def eliminatePieces : Certificate := steps [
  .rule .exchangeExists,
  beneath 1 (.rule .exchangeExists),
  beneath 2 (.rule .exchangeExists),
  beneath 1 (.rule .exchangeExists),
  beneath 3 (.rule .eliminate),
  beneath 2 (.rule .eliminate)]

/--
One input equation; auxiliary equations only arise from Mutate.

X+Y ≈ atom(7)+Z
  -> ∃ p q r t. X≈p+q ∧ Y≈r+t ∧ atom(7)≈p+r ∧ Z≈q+t
  -> allocation p≈0,r≈atom(7) OR p≈atom(7),r≈0 (both retained)
  -> distribute, replace/eliminate p,r, simplify units
  -> the two solved substitution families in overlapOutput.

No call to peelAtom, ACU.peel_atom, or a problem-specific proof occurs here.
-/
def overlapPrimitiveTrace : Certificate := steps [
  .rule .mutate,
  beneath 4 (.right (.right (.left (.seq (.rule .symmetry) (.rule .splitAtom))))),
  beneath 4 (.right (.right (.rule .distributeLeft))),
  beneath 4 (.right (.rule .distributeRight)),
  beneath 4 (.rule .distributeRight),
  extrude 3,
  .left eliminatePieces,
  .right eliminatePieces,
  .rule .swapBranches]

/--
σ₁ = { X ↦ atom(7)+p, Y ↦ q,         Z ↦ p+q }
σ₂ = { X ↦ p,         Y ↦ atom(7)+q, Z ↦ p+q }

No feasibility or arithmetic obligation occurs. The iff quantifies over ALL
ground ACU assignments, including nonempty shared pieces and unit instances.
-/
theorem overlapping_unifiers (X Y Z : V) :
    X +ᵤ Y ≈ᵤ Value.atom 7 +ᵤ Z ↔
      (∃ p q : V, X ≈ᵤ Value.atom 7 +ᵤ p ∧ Y ≈ᵤ q ∧ Z ≈ᵤ p +ᵤ q) ∨
      (∃ p q : V, X ≈ᵤ p ∧ Y ≈ᵤ Value.atom 7 +ᵤ q ∧ Z ≈ᵤ p +ᵤ q) := by
  have certificate := check_exact overlapInput overlapOutput overlapPrimitiveTrace (by decide)
  exact certificate (fun n => match n with | 0 => X | 1 => Y | _ => Z)

/-- A variable occurring on both sides is not automatically an occurs failure. -/
def cycleInput : F := .eqn (.add x y) x

def cycleOutput : F := .eqn y .zero

def cycleTrace : Certificate :=
  .seq (.rule .commLeft) (.seq (.rule .padRight) (.rule .cancel))

theorem unit_cycle (X Y : V) : X +ᵤ Y ≈ᵤ X ↔ Y ≈ᵤ .zero := by
  have certificate := check_exact cycleInput cycleOutput cycleTrace (by decide)
  exact certificate (fun n => match n with | 0 => X | _ => Y)

/-- Four distinct solved substitutions for one equation with four variables. -/
def fourInput : F := .eqn (.add (.add x y) (.add z w)) (.atom 7)

def bothZero (a b : T) : F := .conj (.eqn a .zero) (.eqn b .zero)
def onRight (a b : T) : F := .conj (.eqn a .zero) (.eqn b (.atom 7))
def onLeft (a b : T) : F := .conj (.eqn a (.atom 7)) (.eqn b .zero)

def fourOutput : F :=
  .disj
    (.disj (.conj (bothZero x y) (onRight z w))
           (.conj (bothZero x y) (onLeft z w)))
    (.disj (.conj (onRight x y) (bothZero z w))
           (.conj (onLeft x y) (bothZero z w)))

/-- Focus paths preserve the other branch. Distribute only rearranges logic. -/
def fourTrace : Certificate :=
  .seq (.rule .splitAtom)
    (.seq
      (.left (.seq (.left (.rule .splitZero))
        (.seq (.right (.rule .splitAtom)) (.rule .distributeRight))))
      (.right (.seq (.left (.rule .splitAtom))
        (.seq (.right (.rule .splitZero)) (.rule .distributeLeft)))))

theorem four_unifiers (X Y Z W : V) :
    (X +ᵤ Y) +ᵤ (Z +ᵤ W) ≈ᵤ Value.atom 7 ↔
      (((X ≈ᵤ .zero ∧ Y ≈ᵤ .zero) ∧ (Z ≈ᵤ .zero ∧ W ≈ᵤ .atom 7)) ∨
       ((X ≈ᵤ .zero ∧ Y ≈ᵤ .zero) ∧ (Z ≈ᵤ .atom 7 ∧ W ≈ᵤ .zero))) ∨
      (((X ≈ᵤ .zero ∧ Y ≈ᵤ .atom 7) ∧ (Z ≈ᵤ .zero ∧ W ≈ᵤ .zero)) ∨
       ((X ≈ᵤ .atom 7 ∧ Y ≈ᵤ .zero) ∧ (Z ≈ᵤ .zero ∧ W ≈ᵤ .zero))) := by
  have certificate := check_exact fourInput fourOutput fourTrace (by decide)
  exact certificate (fun n => match n with | 0 => X | 1 => Y | 2 => Z | _ => W)

/-! Negative checks: a well-typed certificate is not automatically accepted. -/

-- The full primitive trace cannot certify just one of the two returned families.
example : check overlapInput
    (.ex (.ex (.conj (.eqn x.lift.lift (.add (.atom 7) (.var 1)))
      (.conj (.eqn y.lift.lift (.var 0)) (.eqn z.lift.lift (.add (.var 1) (.var 0)))))))
    overlapPrimitiveTrace = false := by decide

-- Freshness: x = x+atom(7) cannot be eliminated by a capture-prone substitution.
-- Failure of THIS rule is not an occurs-check theorem about ACU solvability.
example : check (s := Kind.processes)
    (.ex (.conj (.eqn (.var 0) (.add (.var 0) (.atom 7))) .truth))
    .truth (.rule .eliminate) = false := by decide

-- ∃x. x≈y ∧ (∃z. x≈z)  ->  ∃z. y≈z.
-- The outer y becomes index 1 under z, NEVER index 0 (which would capture it).
example : check (s := Kind.processes)
    (.ex (.conj (.eqn (.var 0) (.var 1)) (.ex (.eqn (.var 1) (.var 0)))))
    (.ex (.eqn (.var 1) (.var 0)))
    (steps [.rule .eliminate]) = true := by decide
example : check (s := Kind.processes)
    (.ex (.conj (.eqn (.var 0) (.var 1)) (.ex (.eqn (.var 1) (.var 0)))))
    (.ex (.eqn (.var 0) (.var 0)))
    (steps [.rule .eliminate]) = false := by decide

-- Swapping existential binders also lifts through further nested binders.
example : check (s := Kind.processes)
    (.ex (.ex (.ex (.eqn (.var 2) (.var 0)))))
    (.ex (.ex (.ex (.eqn (.var 1) (.var 0)))))
    (.rule .exchangeExists) = true := by decide

-- Removing a returned unifier must fail, even though the surviving one is sound.
example : check twoInput (.conj (.eqn x .zero) (.eqn y (.atom 7))) twoTrace = false := by
  decide

-- Cancellation checks the common summand syntactically; it does not assume it.
example : check (.eqn (.add x z) (.add y w)) (.eqn x y) (.rule .cancel) = false := by
  decide

-- A different answer is rejected, even with a valid trace for the input.
example : check cycleInput (.eqn x .zero) cycleTrace = false := by decide

-- A supplied atom clash is checked, rather than trusted as a terminal flag.
example : check (s := Kind.processes) (.eqn (.atom 7) (.atom 8)) .falsity
    (.rule .clash) = true := by decide
example : check (s := Kind.processes) (.eqn (.atom 7) (.atom 7)) .falsity
    (.rule .clash) = false := by decide

-- The same rule data works inside existential binders, with de Bruijn scoping.
example : check (s := Kind.processes)
    (.ex (.eqn (.add (.var 0) (.var 1)) .zero))
    (.ex (.conj (.eqn (.var 0) .zero) (.eqn (.var 1) .zero)))
    (.under (.rule .splitZero)) = true := by decide

-- No search, external executable, native_decide, or problem-specific theorem.
#print axioms two_unifiers
#print axioms shared_pieces
#print axioms overlapping_unifiers
#print axioms four_unifiers

end Examples
end Certification2
