name = "conPanna"
version = "0.1.0"
keywords = ["math", "unification", "narrowing"]
defaultTargets = ["Expresso", "conPanna"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[lean_lib]]
name = "Expresso"
roots = ["Expresso.Expresso"]

[[lean_lib]]
name = "conPanna"
roots = ["conPanna.conPanna"]
