import conPanna.conPanna

namespace narrowing_examples

/-!
These examples define an independent user model, constrained patterns, and
rules to demonstrate exact one-step post generation followed by subsumption.
They are clients of both the semantic framework and unification result format.
-/

open framework

/-!
This model, its patterns, and its rules are user code.  In particular, the
model has no constructor for logical variables.
-/
inductive Conf where
  | atom : Nat → Conf
  | pair : Conf → Conf → Conf
  deriving Repr

instance : State Conf := ⟨⟩

open Conf

/-- `pair (atom 0) (atom n) where n > 0` -/
def source (n : Nat) : APattBody Conf where
  term := pair (atom 0) (atom n)
  requires := 0 < n

/-- `pair (atom payload) (atom (payload + 1))` where `payload > 0` -/
def target (payload : Nat) : APattBody Conf where
  term := pair (atom payload) (atom (payload + 1))
  requires := 0 < payload

/-  rl : pair (atom 0) (atom payload)
 => pair (atom payload) (atom next)
 if next = payload + 1` -/
def advance (payload next : Nat) : RuleBody Conf where
  lhs := pair (atom 0) (atom payload)
  rhs := pair (atom payload) (atom next)
  requires := next = payload + 1

-- This is exactly the structural equation used by `narrow`: the rule's two
-- closure arguments come first, followed by the source closure's argument.
-- Its two basis variables become the two binders of the generated `post`.
example
    (h :
      (fun payload next : Nat => (advance payload next).lhs) ⋈
      (fun n : Nat => (source n).term)) : True := by
  unify h
  · unify_complete
  · guard_hyp u1 : Nat
    guard_hyp u2 : Nat
    guard_hyp h1 : payload = u1
    guard_hyp h2 : next = u2
    guard_hyp h3 : n = u1
    -- Substitution in `advance.rhs` gives
    -- `pair (atom u1) (atom u2)`.  Substitution in the source and rule
    -- constraints gives `0 < u1 ∧ u2 = u1 + 1`, exactly the body of `post`
    -- generated by the following narrowing example.
    exact True.intro

example : advance ⊢ source ↪ target := by
  apply mapsInto_via_narrowing
  narrow advance against source
  subsume

/-- A rule whose constructor-headed LHS cannot match `source`. -/
def blocked : RuleBody Conf where
  lhs := pair (atom 1) (atom 0)
  rhs := atom 0

-- With no structural unifier, `narrow` generates the empty post and
-- `subsume` closes its inclusion. No special lemma about `blocked` is supplied.
example : blocked ⊢ source ↪ target := by
  apply mapsInto_via_narrowing
  narrow blocked against source
  subsume

/- This LHS matches `source`, but its constraint requires the matched positive
payload to be zero. -/
def constrainedOut (payload : Nat) : RuleBody Conf where
  lhs := pair (atom 0) (atom payload)
  rhs := atom payload
  requires := payload = 0

-- Structural unification returns an MGU branch.  Its instantiated constraints
-- are `0 < n` and `payload = 0`, so the constraints filter that branch out.
example : constrainedOut ⊢ source ↪ target := by
  apply mapsInto_via_narrowing
  narrow constrainedOut against source
  subsume

end narrowing_examples
