import Mathlib.Data.Multiset.Basic
import Mathlib.Data.Multiset.AddSub
import Mathlib.Data.Multiset.UnionInter
import conPanna.conPanna

set_option conPanna.unification.useMaude true

open framework
open Structural

/-!
# Lamport's Bakery algorithm

This is the constrained-narrowing experiment derived from the earlier Lean
model in `../bakery/bakery.lean` and the DM-Check Bakery example.

The process collection is kept as an ACU constructor language for structural
unification.  Constraints, including `Multiset.Nodup`, remain ordinary Lean
propositions so that feasibility can be established with Lean lemmas.
-/

inductive Mode where
  | idle
  | wait : Nat → Mode
  | crit : Nat → Mode
  deriving Repr

inductive ProcSet where
  | empty
  | singleton : Mode → ProcSet
  | union : ProcSet → ProcSet → ProcSet -- ACU
  deriving Repr

structure Conf where
  next : Nat
  serving : Nat
  procs : ProcSet
  deriving Repr

instance : State Conf := ⟨⟩

structural BakeryTheory where
  assoc ProcSet.union
  comm ProcSet.union
  id ProcSet.union ProcSet.empty

open Mode ProcSet
open scoped Multiset

/- One idle process takes the current ticket. -/
def wake (next serving : Nat) (rest : ProcSet) : RuleBody Conf where
  lhs := {
    next
    serving
    procs := union (singleton idle) rest
  }
  rhs := {
    next := next.succ
    serving
    procs := union (singleton (wait next)) rest
  }
  requires := True

/- The process holding the currently served ticket enters. -/
def enter (next serving : Nat) (rest : ProcSet) : RuleBody Conf where
  lhs := {
    next
    serving
    procs := union (singleton (wait serving)) rest
  }
  rhs := {
    next
    serving
    procs := union (singleton (crit serving)) rest
  }
  requires := True

/- The critical process exits and advances the serving counter. -/
def exit (next serving : Nat) (rest : ProcSet) : RuleBody Conf where
  lhs := {
    next
    serving
    procs := union (singleton (crit serving)) rest
  }
  rhs := {
    next
    serving := serving.succ
    procs := union (singleton idle) rest
  }
  requires := True

def bakeryRules := wake ⊔ enter ⊔ exit

/- A multiset view used only by constraints.  ACU process union is translated
to Mathlib multiset addition, allowing constraints to use its library. -/
def tickets : ProcSet → Multiset Nat
  | empty => 0
  | ProcSet.singleton idle => 0
  | ProcSet.singleton (wait ticket) => {ticket}
  | ProcSet.singleton (crit ticket) => {ticket}
  | union left right => tickets left + tickets right

def allIdle : ProcSet → Prop
  | empty => True
  | ProcSet.singleton mode => mode = idle
  | union left right => allIdle left ∧ allIdle right

def outsideCritical : ProcSet → Prop
  | empty => True
  | ProcSet.singleton idle => True
  | ProcSet.singleton (wait _) => True
  | ProcSet.singleton (crit _) => False
  | union left right => outsideCritical left ∧ outsideCritical right

def ticketsInRange (lower upper : Nat) (procs : ProcSet) : Prop :=
  ∀ ticket ∈ tickets procs, lower ≤ ticket ∧ ticket < upper

/- All processes are idle and both counters agree. -/
def initial (counter : Nat) (procs : ProcSet) : APattBody Conf where
  term := { next := counter, serving := counter, procs }
  requires := allIdle procs

/- No process is critical; outstanding tickets are unique and lie between the
serving and next counters. -/
def waiting (next serving : Nat) (procs : ProcSet) : APattBody Conf where
  term := { next, serving, procs }
  requires :=
    serving < next ∧
    outsideCritical procs ∧
    ticketsInRange serving next procs ∧
    (tickets procs).Nodup

/- Exactly the process with the serving ticket is presented as critical.  The
remainder contains only idle/waiting processes with larger unique tickets. -/
def critical (next serving : Nat) (rest : ProcSet) : APattBody Conf where
  term := {
    next
    serving
    procs := union (singleton (crit serving)) rest
  }
  requires :=
    serving < next ∧
    outsideCritical rest ∧
    (∀ ticket ∈ tickets rest, serving < ticket ∧ ticket < next) ∧
    (tickets rest).Nodup

def bakeryInv := initial ⊔ waiting ⊔ critical

/- A deliberately small first constrained-narrowing target.  It isolates the
ACU overlap used by `wake` while retaining a nontrivial Lean constraint. -/
def idleWithUniqueTickets
    (next serving : Nat) (rest : ProcSet) : APattBody Conf where
  term := {
    next
    serving
    procs := union (singleton idle) rest
  }
  requires := (tickets rest).Nodup

def enterLeft (next serving : Nat) (rest : ProcSet) : APattBody Conf :=
  (enter next serving rest).leftPat

/- These definitions are generated by the same overlap materialization used by
constrained `#unify`; no Bakery-specific substitution is written manually. -/
def enterInitialPost := narrow enter from initial mod BakeryTheory
def enterWaitingPost := narrow enter from waiting mod BakeryTheory

#print enterInitialPost

-- First experiment: structural ACU unification should compute the successor
-- while carrying the source's `Nodup` constraint into the generated post.
#narrow wake from idleWithUniqueTickets mod BakeryTheory

/- These two probes have the same structurally applicable `enter` rule but
different constraints.  The initial branch should retain an infeasible
`allIdle` constraint, whereas the waiting branch may remain feasible. -/
#narrow enter from initial mod BakeryTheory
#narrow enter from waiting mod BakeryTheory

-- Constrained `#unify` now computes the overlap patterns underlying those
-- narrowing steps, rather than exposing only structural substitutions.
#unify enterLeft with initial mod BakeryTheory
#unify enterLeft with waiting mod BakeryTheory

/- The first generated residual constraint is infeasible: structural
unification inserted a waiting process into a collection constrained to be
entirely idle. -/
lemma enter_initial_constraint_infeasible (ticket : Nat) (rest : ProcSet) :
    ¬ (enterInitialPost ticket rest).requires := by
  simp [enterInitialPost, allIdle]

/- The second residual constraint is not merely syntactically consistent.  A
single process waiting with ticket zero gives it a concrete Lean witness. -/
lemma enter_waiting_constraint_feasible :
    ∃ next serving rest,
      (enterWaitingPost next serving rest).requires := by
  refine ⟨1, 0, empty, ?_⟩
  simp [enterWaitingPost, outsideCritical, ticketsInRange, tickets]

-- Full experiments to enable once constrained unification exposes residual
-- constraints cleanly:
/- Named posts isolate subsumption automation from narrowing certification. -/
def wakeInvariantPost := narrow wake from bakeryInv mod BakeryTheory
#narrow enter from bakeryInv mod BakeryTheory
def exitInvariantPost := narrow exit from bakeryInv mod BakeryTheory
-- #narrow bakeryRules from bakeryInv mod BakeryTheory

macro "bakery_subsume" : tactic =>
  `(tactic|
    simp only [framework.Patterns.SubsumesMod,
      framework.Patterns.PatternMod.semantics,
      framework.Patterns.APattMod.semantics,
      bakeryInv, initial, waiting, critical] <;>
    simp_all [allIdle, outsideCritical, ticketsInRange, tickets,
      Multiset.nodup_add] <;>
    grind)

example : enter ⊢ bakeryInv ↪[BakeryTheory] bakeryInv := by
  apply mapsInto_via_narrowing_mod
  narrow enter from bakeryInv mod BakeryTheory := by
    sorry
  subsume_cases
  · bakery_subsume
  · bakery_subsume
  · bakery_subsume

example : wakeInvariantPost ⊑[BakeryTheory] bakeryInv := by
  subsume_cases
  -- None of the three branches is closed by the unchanged automation yet.
  · fail_if_success bakery_subsume
    sorry
  · fail_if_success bakery_subsume
    sorry
  · fail_if_success bakery_subsume
    sorry

example : exitInvariantPost ⊑[BakeryTheory] bakeryInv := by
  subsume_cases
  -- The three infeasible overlaps close automatically.
  · bakery_subsume
  · bakery_subsume
  · bakery_subsume
  -- The feasible overlap requires a successor/equality case split.
  · fail_if_success bakery_subsume
    sorry
