import Mathlib.Data.Multiset.AddSub
import conPanna.conPanna

set_option conPanna.unification.useMaude true

open framework
open Structural

/-!
# Fair readers-writers with symbolic ACU counts

`Count` is the free commutative-monoid term language generated by `one`.
Configurations use named fields and a Boolean writer flag; this keeps the Lean
model independent of the concrete notation and overloaded sorts of the source
Maude specification.
-/

inductive Count where
  | zero
  | one
  | add : Count → Count → Count
  deriving Repr

namespace Count

-- for notational convenience
instance : OfNat Count 0 := ⟨zero⟩
instance : OfNat Count 1 := ⟨one⟩
instance : Add Count := ⟨add⟩

end Count

structure Conf where
  total : Count
  readers : Count
  writer : Bool
  before : Count
  after : Count
  deriving Repr

instance : State Conf := ⟨⟩

-- Declaring the theory after the state lets `structural` register the ordinary
-- constructors needed to lift ACU equality through `Conf` automatically.
structural B where
  assoc Count.add
  comm Count.add
  id Count.add Count.zero

-- shows automatically generated maude module used in tactics
#dump_maude_model Conf mod B

open Count

/- The writer enters when no reader is active and every reader is in `after`. -/
def writerIn (n : Count) : RuleBody Conf where
  lhs := {
    total := n, readers := 0, writer := false, before := 0, after := n
  }
  rhs := {
    total := n, readers := 0, writer := true, before := 0, after := n
  }
  requires := True

/- On exit, the writer moves all readers from `after` to `before`. -/
def writerOut (n : Count) : RuleBody Conf where
  lhs := {
    total := n, readers := 0, writer := true, before := 0, after := n
  }
  rhs := {
    total := n, readers := 0, writer := false, before := n, after := 0
  }
  requires := True

/- One reader moves from `before` into the critical section. -/
def readerIn (k n m : Count) : RuleBody Conf where
  lhs := {
    total := k + n + m + 1
    readers := n
    writer := false
    before := m + 1
    after := k
  }
  rhs := {
    total := k + n + m + 1
    readers := n + 1
    writer := false
    before := m
    after := k
  }
  requires := True

/- One active reader leaves and joins `after`. -/
def readerOut (k n m : Count) : RuleBody Conf where
  lhs := {
    total := k + n + m + 1
    readers := n + 1
    writer := false
    before := m
    after := k
  }
  rhs := {
    total := k + n + m + 1
    readers := n
    writer := false
    before := m
    after := k + 1
  }
  requires := True

/- Readers are circulating from `before`, through the critical section, to
`after`; at least one reader remains after the writer. -/
def readersAfter (n m k : Count) : APattBody Conf where
  term := {
    total := n + m + k + 1
    readers := n
    writer := false
    before := m
    after := k + 1
  }
  requires := True

/- The writer is active and every reader is in `after`. -/
def writerActive (n : Count) : APattBody Conf where
  term := {
    total := n + 1
    readers := 0
    writer := true
    before := 0
    after := n + 1
  }
  requires := True

/- At least one reader is still waiting in `before`. -/
def readersBefore (n m k : Count) : APattBody Conf where
  term := {
    total := n + m + 1 + k
    readers := n
    writer := false
    before := m + 1
    after := k
  }
  requires := True

/- At least one reader is active. -/
def readersActive (n m k : Count) : APattBody Conf where
  term := {
    total := n + 1 + m + k
    readers := n + 1
    writer := false
    before := m
    after := k
  }
  requires := True

def rwFairInv :=
  readersAfter ⊔ writerActive ⊔ readersBefore ⊔ readersActive



/- A small ACU probe: `one` can be assigned to either labeled summand on the
right, so a complete solver must return two incomparable unifiers. -/
def splitLeft (x : Count) : Conf where
  total := x + 1
  readers := 0
  writer := false
  before := 0
  after := 0

def splitRight (a b : Count) : Conf where
  total := a + b
  readers := 0
  writer := false
  before := 0
  after := 0

-- #unify splitLeft with splitRight mod B

-- #narrow writerIn from rwFairInv mod B
-- #narrow writerOut from rwFairInv mod B
-- #narrow readerIn from rwFairInv mod B
-- #narrow readerOut from rwFairInv mod B

example : writerIn ⊢ rwFairInv ↪[B] rwFairInv := by
  apply mapsInto_via_narrowing_mod
  narrow writerIn from rwFairInv mod B := by
    sorry
  subsume_cases
  · -- subsume_atom works
    intro state hpost
    rcases hpost with ⟨u, hstate, _⟩
    refine Or.inr (Or.inl ⟨u, ?_, True.intro⟩)
    exact Structural.EqMod.transAt B (by structural_rfl) hstate

example : writerOut ⊢ rwFairInv ↪[B] rwFairInv := by
  apply mapsInto_via_narrowing_mod
  narrow writerOut from rwFairInv mod B := by
    sorry
  subsume_cases
  · subsume_atom -- readersBefore

example : readerIn ⊢ rwFairInv ↪[B] rwFairInv := by
  apply mapsInto_via_narrowing_mod
  narrow readerIn from rwFairInv mod B := by
    sorry
  subsume_cases
  · subsume_atom -- readersActive
  · subsume_atom -- readersActive
  · subsume_atom -- readersActive

example : readerOut ⊢ rwFairInv ↪[B] rwFairInv := by
  apply mapsInto_via_narrowing_mod
  narrow readerOut from rwFairInv mod B := by
    sorry
  subsume_cases
  · subsume_atom -- readersAfter
  · subsume_atom -- readersAfter
  · subsume_atom -- readersAfter


/- The complete transition relation is the nondeterministic choice of the four
atomic rules. -/
def rwFairRules :=
  writerIn ⊔ writerOut ⊔ readerIn ⊔ readerOut

-- #narrow rwFairRules from rwFairInv mod B

example : rwFairRules ⊢ rwFairInv ↪[B] rwFairInv := by
  apply mapsInto_via_narrowing_mod
  narrow rwFairRules from rwFairInv mod B := by
    sorry
  subsume -- 8 atomic patterns


#print rwFairRules


/- todo: invariant generation -> narrowing search -/

/- do another equivalent proof using rule-comp
below holds because it is about single step (bidirectional)
  R1 ⊢ S ↪[B] T   R2 ⊢ S ↪[B] T
==================================[RuleComp]
       R1 ⊔ R2 ⊢ S ↪[B] T

R₁* ⊢ S ↪[B] T    R₂* ⊢ S ↪[B] T
──────────────────────────────────  INVALID!!
        (R₁ ⊔ R₂)* ⊢ S ↪[B] T
-/

/- what about these?
  R ⊢ S ↪[B] T    S' ⊆ S
---------------------
 R ⊢ S' ↪[B] T

  R ⊢ S ↪[B] T    T ⊆ T'
----------------------
 R ⊢ S ↪[B] T'

  R ⊢ S₁ ↪ T   R ⊢ S₂ ↪ T
──────────────────────────(bidirectional)
      R ⊢ S₁ ⊔ S₂ ↪ T

R ⊢ S ↪ T₁   R ⊢ S ↪ T₂
──────────────────────────(bidirectional)
      R ⊢ S ↪ T₁ ⊓ T₂

  R ⊢ I ↪ I
────────────────
  R* ⊢ I ↪ I

  S ⊑ I    R₁ ⊢ I ↪[B] I    R₂ ⊢ I ↪[B] I    I ⊑ T
  ─────────────────────────────────────────────────── [StarInd]
               Q* ⊢ S ↪[B] T

  R₁ ⊢ I ↪[B] I    R₂ ⊢ I ↪[B] I
  ──────────────────────────────── [StarInv]
         (R₁ ⊔ R₂)* ⊢ I ↪[B] I

-/

/-!
## Optional Mathlib multiset view

This experiment is deliberately separate from the ordinary narrowing proofs.
-/

/-!
### Library-side API prototype

This generic definition and theorem should eventually move into `conPanna`.
They are not specific to `Count` or the readers-writers model.
-/

namespace Structural

structure MultisetView (theory : Theory) (Term Atom : Type) where
  encode : Term → Multiset Atom
  decode : Multiset Atom → Term
  normalize : ∀ term, term =[theory] decode (encode term)

theorem MultisetView.eqMod_of_eq
    {theory : Theory} {Term Atom : Type}
    (view : MultisetView theory Term Atom) {left right : Term}
    (equality : view.encode left = view.encode right) :
    left =[theory] right := by
  exact EqMod.transAt theory (view.normalize left) <|
    EqMod.transAt theory
      (.ofEq (congrArg view.decode equality))
      (.symm (view.normalize right))

end Structural

/-!
### Generated model bridge prototype

This block is model-specific, but a future extension of `structural B` should
generate it.  An end user should not have to write or inspect these proofs.
-/

namespace Count

def toMultiset : Count → Multiset Unit
  | zero => 0
  | one => {()}
  | add left right => left.toMultiset + right.toMultiset

@[simp] theorem toMultiset_zero : zero.toMultiset = 0 := rfl
@[simp] theorem toMultiset_one : one.toMultiset = {()} := rfl
@[simp] theorem toMultiset_add (left right : Count) :
    (add left right).toMultiset = left.toMultiset + right.toMultiset := rfl

private def fromCard : Nat → Count
  | 0 => zero
  | n + 1 => add one (fromCard n)

private theorem fromCard_add (left right : Nat) :
    add (fromCard left) (fromCard right) =[B] fromCard (left + right) := by
  induction left with
  | zero =>
      simpa [fromCard] using
        (Structural.EqMod.identityLeft (theory := B)
          Count.add Count.zero (fromCard right))
  | succ left ih =>
      simpa [fromCard, Nat.succ_add] using Structural.EqMod.transAt B
        (.assoc Count.add Count.one (fromCard left) (fromCard right))
        (.congr Count.add (.ofEq rfl) ih)

private theorem eqMod_normalize (value : Count) :
    value =[B] fromCard value.toMultiset.card := by
  induction value with
  | zero => exact .ofEq rfl
  | one => exact .symm (.identityRight Count.add Count.zero Count.one)
  | add left right leftIH rightIH =>
      simpa using Structural.EqMod.transAt B
        (.congr Count.add leftIH rightIH)
        (fromCard_add left.toMultiset.card right.toMultiset.card)

def multisetView : Structural.MultisetView B Count Unit where
  encode := toMultiset
  decode := fromCard ∘ Multiset.card
  normalize := eqMod_normalize

theorem viaMultiset {left right : Count}
    (equality : left.toMultiset = right.toMultiset) : left =[B] right := by
  exact multisetView.eqMod_of_eq equality

end Count

/-!
### User-level proof

Only this part should remain handwritten in the model's user file.
-/

example : writerIn ⊢ rwFairInv ↪[B] rwFairInv := by
  apply mapsInto_via_narrowing_mod
  narrow writerIn from rwFairInv mod B := by
    sorry
  subsume_cases
  · intro state hpost
    rcases hpost with ⟨u, hstate, _⟩
    refine Or.inr (Or.inl ⟨u, ?_, True.intro⟩)
    apply Structural.EqMod.transAt B ?_ hstate
    change
      Conf.mk (Count.add u Count.one) Count.zero true Count.zero
          (Count.add u Count.one) =[B]
        Conf.mk (Count.add Count.one u) Count.zero true Count.zero
          (Count.add Count.one u)
    have hcount : (u + 1) =[B] (1 + u) := by
      apply Count.viaMultiset
      exact Multiset.add_comm _ _
    exact Structural.EqMod.constructorAt B <|
      .app (.app (.app (.app (.app (.head Conf.mk)
        hcount) (.ofEq rfl)) (.ofEq rfl)) (.ofEq rfl)) hcount
