import conPanna.conPanna

set_option conPanna.unification.useMaude true

open framework
open Structural

/-!
# Fair readers-writers with symbolic ACU counts

`Count` is the free commutative-monoid term language generated by `one`.
Configurations use named fields and a Boolean writer flag; this keeps the Lean
model independent of the concrete notation and overloaded sorts of the source
Maude specification.
-/

inductive Count where
  | zero
  | one
  | add : Count → Count → Count
  deriving Repr

namespace Count

instance : OfNat Count 0 := ⟨zero⟩
instance : OfNat Count 1 := ⟨one⟩
instance : Add Count := ⟨add⟩

end Count

structure Conf where
  total : Count
  readers : Count
  writer : Bool
  before : Count
  after : Count
  deriving Repr

instance : State Conf := ⟨⟩

-- Declaring the theory after the state lets `structural` register the ordinary
-- constructors needed to lift ACU equality through `Conf` automatically.
structural B where
  assoc Count.add
  comm Count.add
  id Count.add Count.zero

open Count

/- The writer enters when no reader is active and every reader is in `after`. -/
def writerIn (n : Count) : RuleBody Conf where
  lhs := {
    total := n, readers := 0, writer := false, before := 0, after := n
  }
  rhs := {
    total := n, readers := 0, writer := true, before := 0, after := n
  }
  requires := True

/- On exit, the writer moves all readers from `after` to `before`. -/
def writerOut (n : Count) : RuleBody Conf where
  lhs := {
    total := n, readers := 0, writer := true, before := 0, after := n
  }
  rhs := {
    total := n, readers := 0, writer := false, before := n, after := 0
  }
  requires := True

/- One reader moves from `before` into the critical section. -/
def readerIn (k n m : Count) : RuleBody Conf where
  lhs := {
    total := k + n + m + 1
    readers := n
    writer := false
    before := m + 1
    after := k
  }
  rhs := {
    total := k + n + m + 1
    readers := n + 1
    writer := false
    before := m
    after := k
  }
  requires := True

/- One active reader leaves and joins `after`. -/
def readerOut (k n m : Count) : RuleBody Conf where
  lhs := {
    total := k + n + m + 1
    readers := n + 1
    writer := false
    before := m
    after := k
  }
  rhs := {
    total := k + n + m + 1
    readers := n
    writer := false
    before := m
    after := k + 1
  }
  requires := True

/- Readers are circulating from `before`, through the critical section, to
`after`; at least one reader remains after the writer. -/
def readersAfter (n m k : Count) : APattBody Conf where
  term := {
    total := n + m + k + 1
    readers := n
    writer := false
    before := m
    after := k + 1
  }
  requires := True

/- The writer is active and every reader is in `after`. -/
def writerActive (n : Count) : APattBody Conf where
  term := {
    total := n + 1
    readers := 0
    writer := true
    before := 0
    after := n + 1
  }
  requires := True

/- At least one reader is still waiting in `before`. -/
def readersBefore (n m k : Count) : APattBody Conf where
  term := {
    total := n + m + 1 + k
    readers := n
    writer := false
    before := m + 1
    after := k
  }
  requires := True

/- At least one reader is active. -/
def readersActive (n m k : Count) : APattBody Conf where
  term := {
    total := n + 1 + m + k
    readers := n + 1
    writer := false
    before := m
    after := k
  }
  requires := True

def rwFairInv :=
  readersAfter ⊔ writerActive ⊔ readersBefore ⊔ readersActive

/- A small ACU probe: `one` can be assigned to either labeled summand on the
right, so a complete solver must return two incomparable unifiers. -/
def splitLeft (x : Count) : Conf where
  total := x + 1
  readers := 0
  writer := false
  before := 0
  after := 0

def splitRight (a b : Count) : Conf where
  total := a + b
  readers := 0
  writer := false
  before := 0
  after := 0

#unify splitLeft with splitRight mod B

#narrow writerIn from rwFairInv mod B
#narrow writerOut from rwFairInv mod B
#narrow readerIn from rwFairInv mod B
#narrow readerOut from rwFairInv mod B

example : writerIn ⊢ rwFairInv ↪[B] rwFairInv := by
  apply mapsInto_via_narrowing_mod
  narrow writerIn from rwFairInv mod B := by
    sorry
  subsume_cases
  · -- subsume_atom works
    intro state hpost
    rcases hpost with ⟨u, hstate, _⟩
    refine Or.inr (Or.inl ⟨u, ?_, True.intro⟩)
    exact Structural.EqMod.transAt B (by structural_rfl) hstate

example : writerOut ⊢ rwFairInv ↪[B] rwFairInv := by
  apply mapsInto_via_narrowing_mod
  narrow writerOut from rwFairInv mod B := by
    sorry
  subsume_cases
  · subsume_atom -- readersBefore

example : readerIn ⊢ rwFairInv ↪[B] rwFairInv := by
  apply mapsInto_via_narrowing_mod
  narrow readerIn from rwFairInv mod B := by
    sorry
  subsume_cases
  · subsume_atom -- readersActive
  · subsume_atom -- readersActive
  · subsume_atom -- readersActive

example : readerOut ⊢ rwFairInv ↪[B] rwFairInv := by
  apply mapsInto_via_narrowing_mod
  narrow readerOut from rwFairInv mod B := by
    sorry
  subsume_cases
  · subsume_atom -- readersAfter
  · subsume_atom -- readersAfter
  · subsume_atom -- readersAfter
