import Lean

/-!
A prototype declarative interface for Maude-style structural equations.
Unlike `Theory.OperatorLaw`, these declarations generate witnesses consumed by
`EqMod`; they do not assert that raw Lean constructors are equal.
-/
namespace Structural

universe u

/-- A structural equation attached to the operation it governs. -/
inductive OperatorLaw : {operationType : Type u} →
    (operation : operationType) → Type (u + 1) where
  | commutative {α β : Type u} {operation : α → α → β} :
      OperatorLaw operation
  | associative {α : Type u} {operation : α → α → α} :
      OperatorLaw operation
  | identity {α : Type u} {operation : α → α → α} (element : α) :
      OperatorLaw operation

/-- One symbol together with the equations declared for that symbol. -/
structure Symbol where
  {operationType : Type u}
  operation : operationType
  laws : List (OperatorLaw operation) := []

def Symbol.declare {operationType : Type u} (operation : operationType)
    (laws : List (OperatorLaw operation) := []) : Symbol where
  operation := operation
  laws := laws

/-- A collection of independently classified structural symbols. -/
structure CommutativeDeclaration where
  {inputType outputType : Type u}
  operation : inputType → inputType → outputType

def CommutativeDeclaration.declare {α β : Type u}
    (operation : α → α → β) : CommutativeDeclaration where
  operation := operation

structure AssociativeDeclaration where
  {carrier : Type u}
  operation : carrier → carrier → carrier

def AssociativeDeclaration.declare {α : Type u}
    (operation : α → α → α) : AssociativeDeclaration where
  operation := operation

structure IdentityDeclaration where
  {carrier : Type u}
  operation : carrier → carrier → carrier
  element : carrier

def IdentityDeclaration.declare {α : Type u}
    (operation : α → α → α) (element : α) : IdentityDeclaration where
  operation := operation
  element := element

structure Theory where
  symbols : List (Symbol.{u}) := []
  commutative : List (CommutativeDeclaration.{u}) := []
  associative : List (AssociativeDeclaration.{u}) := []
  identities : List (IdentityDeclaration.{u}) := []

/-- Proof-level evidence that a theory declares an operation commutative. -/
class HasComm (theory : Theory.{u}) {α β : Type u}
    (operation : α → α → β) where
  declaration : CommutativeDeclaration.{u}
  member : declaration ∈ theory.commutative
  operation_eq : HEq declaration.operation operation

/-- Proof-level evidence that a theory declares an operation associative. -/
class HasAssoc (theory : Theory.{u}) {α : Type u}
    (operation : α → α → α) where
  declaration : AssociativeDeclaration.{u}
  member : declaration ∈ theory.associative
  operation_eq : HEq declaration.operation operation

/-- Proof-level evidence that a theory declares a two-sided identity. -/
class HasIdentity (theory : Theory.{u}) {α : Type u}
    (operation : α → α → α) (element : α) where
  declaration : IdentityDeclaration.{u}
  member : declaration ∈ theory.identities
  operation_eq : HEq declaration.operation operation
  element_eq : HEq declaration.element element

/--
Equality generated by native Lean equality, congruence, and the structural
laws registered in `theory`.  In particular, a raw constructor can be treated
as commutative here without asserting an impossible equality between distinct
constructor trees.
-/
inductive EqMod (theory : Theory.{u}) : {α : Type u} → α → α → Prop where
  | ofEq {α : Type u} {left right : α} (equality : left = right) :
      EqMod theory left right
  | symm {α : Type u} {left right : α} :
      EqMod theory left right → EqMod theory right left
  | trans {α : Type u} {first second third : α} :
      EqMod theory first second → EqMod theory second third →
        EqMod theory first third
  | congr {α β : Type u} (function : α → β) {left right : α} :
      EqMod theory left right → EqMod theory (function left) (function right)
  | comm {α β : Type u} (operation : α → α → β)
      [HasComm theory operation] (left right : α) :
      EqMod theory (operation left right) (operation right left)
  | assoc {α : Type u} (operation : α → α → α)
      [HasAssoc theory operation] (first second third : α) :
      EqMod theory (operation (operation first second) third)
        (operation first (operation second third))
  | identityLeft {α : Type u} (operation : α → α → α) (element value : α)
      [HasIdentity theory operation element] :
      EqMod theory (operation element value) value
  | identityRight {α : Type u} (operation : α → α → α) (element value : α)
      [HasIdentity theory operation element] :
      EqMod theory (operation value element) value

namespace EqMod

theorem reflAt (theory : Theory.{u}) {α : Type u} (value : α) :
    EqMod theory value value :=
  .ofEq rfl

theorem transAt (theory : Theory.{u}) {α : Type u}
    {first second third : α} :
    EqMod theory first second → EqMod theory second third →
      EqMod theory first third :=
  .trans

theorem congrAt (theory : Theory.{u}) {α β : Type u}
    (function : α → β) {left right : α} :
    EqMod theory left right → EqMod theory (function left) (function right) :=
  .congr function

theorem commAt (theory : Theory.{u}) {α β : Type u}
    (operation : α → α → β) [HasComm theory operation]
    (left right : α) :
    EqMod theory (operation left right) (operation right left) :=
  .comm operation left right

end EqMod

end Structural


open Lean Elab Command

declare_syntax_cat structuralLaw

namespace Structural

scoped syntax "comm " term : structuralLaw
scoped syntax "assoc " term : structuralLaw
scoped syntax "id " term:max term : structuralLaw

end Structural

open scoped Structural

/-- Declare a named collection of Maude-style structural equations. -/
syntax (name := structuralCommand)
  "structural " ident " where" ppLine structuralLaw* : command

private structure StructuralGroup where
  operation : TSyntax `term
  laws : Array (TSyntax `term)
  deriving Inhabited

private def addStructuralLaw (groups : Array StructuralGroup)
    (operation law : TSyntax `term) : Array StructuralGroup := Id.run do
  let mut groups := groups
  for index in [:groups.size] do
    if groups[index]!.operation.raw == operation.raw then
      let group := groups[index]!
      groups := groups.set! index { group with laws := group.laws.push law }
      return groups
  return groups.push { operation, laws := #[law] }

elab_rules : command
  | `(structural $name:ident where $laws:structuralLaw*) => do
      let mut groups : Array StructuralGroup := #[]
      let mut commutativeOperations : Array (TSyntax `term) := #[]
      let mut associativeOperations : Array (TSyntax `term) := #[]
      let mut identities : Array (TSyntax `term × TSyntax `term) := #[]
      for law in laws do
        match law with
        | `(structuralLaw| comm $operation:term) =>
            let declaration ← `(term| Structural.OperatorLaw.commutative)
            groups := addStructuralLaw groups operation declaration
            unless commutativeOperations.any fun existing =>
                existing.raw == operation.raw do
              commutativeOperations := commutativeOperations.push operation
        | `(structuralLaw| assoc $operation:term) =>
            let declaration ← `(term| Structural.OperatorLaw.associative)
            groups := addStructuralLaw groups operation declaration
            unless associativeOperations.any fun existing =>
                existing.raw == operation.raw do
              associativeOperations := associativeOperations.push operation
        | `(structuralLaw| id $operation:term $element:term) =>
            let declaration ← `(term| Structural.OperatorLaw.identity $element)
            groups := addStructuralLaw groups operation declaration
            unless identities.any fun existing =>
                existing.1.raw == operation.raw &&
                  existing.2.raw == element.raw do
              identities := identities.push (operation, element)
        | _ => throwUnsupportedSyntax

      let mut symbols : Array (TSyntax `term) := #[]
      for group in groups do
        let declaration ← `(term|
          Structural.Symbol.declare $(group.operation) [$(group.laws),*])
        symbols := symbols.push declaration
      let symbolList ← `(term| [$symbols,*])

      let mut commutativeDeclarations : Array (TSyntax `term) := #[]
      for operation in commutativeOperations do
        commutativeDeclarations := commutativeDeclarations.push
          (← `(term| Structural.CommutativeDeclaration.declare $operation))
      let commutativeList ← `(term| [$commutativeDeclarations,*])

      let mut associativeDeclarations : Array (TSyntax `term) := #[]
      for operation in associativeOperations do
        associativeDeclarations := associativeDeclarations.push
          (← `(term| Structural.AssociativeDeclaration.declare $operation))
      let associativeList ← `(term| [$associativeDeclarations,*])

      let mut identityDeclarations : Array (TSyntax `term) := #[]
      for (operation, element) in identities do
        identityDeclarations := identityDeclarations.push
          (← `(term|
            Structural.IdentityDeclaration.declare $operation $element))
      let identityList ← `(term| [$identityDeclarations,*])

      elabCommand (← `(command|
        def $name : Structural.Theory where
          symbols := $symbolList
          commutative := $commutativeList
          associative := $associativeList
          identities := $identityList))
      for operation in commutativeOperations do
        elabCommand (← `(command|
          instance : Structural.HasComm $name $operation where
            declaration := Structural.CommutativeDeclaration.declare $operation
            member := by simp [$(name):ident]
            operation_eq := HEq.rfl))
      for operation in associativeOperations do
        elabCommand (← `(command|
          instance : Structural.HasAssoc $name $operation where
            declaration := Structural.AssociativeDeclaration.declare $operation
            member := by simp [$(name):ident]
            operation_eq := HEq.rfl))
      for (operation, element) in identities do
        elabCommand (← `(command|
          instance : Structural.HasIdentity $name $operation $element where
            declaration :=
              Structural.IdentityDeclaration.declare $operation $element
            member := by simp [$(name):ident]
            operation_eq := HEq.rfl
            element_eq := HEq.rfl))
